<?php 
 $fis_data=
Array
(
"tplData" => array
(
"orderList" => array
(
"code" => "0",
"msg" => "ok",
"data" => array
(
"data" => array
(
"0" => array
(
"id" => "1123",
"orderId" => "215072073095765218609",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1169",
"colorId" => "1",
"colorName" => "宝石青",
"brandId" => "5",
"subBrandId" => "7",
"serieId" => "64",
"autoId" => "536",
"userName" => "_TEST_",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23202",
"pointId" => "23202",
"price" => "0.02",
"emaoPrice" => "342200.00",
"couponValue" => "0.00",
"gType" => "2",
"insertTime" => "2015-07-20 14:18:15",
"cancelTime" => "0",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "13718863804",
"payType" => "1",
"payTime" => "1437373138",
"payTradeNo" => "2015072000001000810060148906",
"state" => "2",
"gift" => array
(
"id" => "19",
"type" => "1",
"cover" => "/mall/nd/bak/hsyn.jpg",
"name" => "100元超市卡",
"price" => "100.00",
"descr" => "100元超市卡",
"addTime" => "1431486338",
"addUser" => "qiuerke136@emao.com",
"state" => "1",
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "428325875672",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "21507207309576521860991",
"deposit" => "0.02",
"couponSellPrice" => "0.00",
"offlinePrice" => "342199.98",
"offlineReduce" => "",
"goods" => array
(
"id" => "1169",
"consumerId" => "23202",
"sellType" => "4",
"brandId" => "5",
"subBrandId" => "7",
"serieId" => "64",
"autoId" => "536",
"smsTitle" => "自采，普通售卖，整车，必须上传，不显示库存，允许使用优惠券",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p>自采，普通售卖，整车，必须上传，不显示库存，允许使用优惠券自采，普通售卖，整车，必须上传，不显示库存，允许使用优惠券</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p>自采，普通售卖，整车，必须上传，不显示库存，允许使用优惠券自采，普通售卖，整车，必须上传，不显示库存，允许使用优惠券</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p><br/></p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p>自采，普通售卖，整车，必须上传，不显示库存，允许使用优惠券</p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p>自采，普通售卖，整车，必须上传，不显示库存，允许使用优惠券</p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1437133171",
"updateTime" => "1437133283",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1437133191",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1437133269",
"backTime" => "1437133264",
"preSellTime" => "1437132600",
"sellTime" => "1437132600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1438342200",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "53",
"sortState" => "53",
"description" => "自采，普通售卖，整车，必须上传，不显示库存，允许使用优惠券",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1438342200",
"sellLead" => "自采，普通售卖，整车，必须上传，不显示库存，允许使用优惠券",
"num" => "9",
"minPrice" => "342200.00",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "64.56",
"autoName" => "{"brandName":"宝马","subBrandName":"华晨宝马","serieName":"宝马5系","autoName":"528Li xDrive风尚设计套装"}",
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "2",
"goodsName" => "2014-528Li xDrive风尚设计套装",
"stockType" => "1",
"finalTimeWap" => "2015-07-31 19:30:00",
"serieName" => "华晨宝马 宝马5系 528Li xDrive风尚设计套装",
"images" => array
(
"0" => array
(
"id" => "953",
"gid" => "1169",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/gbsv.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437133257",
),
"1" => array
(
"id" => "954",
"gid" => "1169",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/iwkw.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437133257",
),
"2" => array
(
"id" => "955",
"gid" => "1169",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/sjb.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437133257",
),
"3" => array
(
"id" => "956",
"gid" => "1169",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/bema.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437133257",
),
"4" => array
(
"id" => "957",
"gid" => "1169",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/erjd.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "2",
"insertTime" => "1437133257",
),
),
),
"dealer" => array
(
"23202" => array
(
"dealerid" => "23202",
"name" => "G商城测试商户A",
"member" => "4S店",
"linkName" => "测试任君生",
"linkPhone" => "15810722228",
"telephone" => "15810722228",
"address" => "北京北京",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.445192",
"latitude" => "39.928740",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"2" => array
(
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "2",
"subBrand" => array
(
"2" => array
(
"id" => "2",
"subBrandName" => "一汽奥迪",
"sub_brandid" => "2",
),
),
),
"5" => array
(
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "5",
"subBrand" => array
(
"7" => array
(
"id" => "7",
"subBrandName" => "华晨宝马",
"sub_brandid" => "7",
),
"9" => array
(
"id" => "9",
"subBrandName" => "宝马M",
"sub_brandid" => "9",
),
),
),
"8" => array
(
"brandName" => "奔驰",
"logo" => "http://img.emao.net/car/logo/nd/bah/hboc.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "8",
"subBrand" => array
(
"12" => array
(
"id" => "12",
"subBrandName" => "北京奔驰",
"sub_brandid" => "12",
),
"13" => array
(
"id" => "13",
"subBrandName" => "福建奔驰",
"sub_brandid" => "13",
),
"15" => array
(
"id" => "15",
"subBrandName" => "奔驰AMG",
"sub_brandid" => "15",
),
"204" => array
(
"id" => "204",
"subBrandName" => "奔驰-迈巴赫",
"sub_brandid" => "204",
),
),
),
),
),
),
"invoice" => array
(
"name" => "_TEST_",
"phone" => "13718863804",
"VIN" => "",
"price" => "342200.00",
),
"ticketInfo" => array
(
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
"1" => array
(
"id" => "1115",
"orderId" => "215071731311865404103",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1163",
"colorId" => "1",
"colorName" => "夜晚黑",
"brandId" => "8",
"subBrandId" => "14",
"serieId" => "135",
"autoId" => "12370",
"userName" => "抵扣券6000不允许使用券",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23202",
"pointId" => "23202",
"price" => "0.04",
"emaoPrice" => "305000.00",
"couponValue" => "6000.00",
"gType" => "1",
"insertTime" => "2015-07-17 19:08:31",
"cancelTime" => "0",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "",
"payType" => "",
"payTime" => "0",
"payTradeNo" => "",
"state" => "1",
"gift" => array
(
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "0",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "",
"deposit" => "0.00",
"couponSellPrice" => "0.04",
"offlinePrice" => "299000",
"offlineReduce" => "6000.00",
"goods" => array
(
"id" => "1163",
"consumerId" => "23202",
"sellType" => "4",
"brandId" => "8",
"subBrandId" => "14",
"serieId" => "135",
"autoId" => "12370",
"smsTitle" => "否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p>否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券</p></div>",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1437114964",
"updateTime" => "1437115021",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1437114981",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1437114986",
"backTime" => "",
"preSellTime" => "1437114600",
"sellTime" => "1437114600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439015400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "150",
"sortState" => "150",
"description" => "否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1438324200",
"sellLead" => "否自采，普通售卖，抵扣券，必须上传，不显示库存，不允许使用优惠券",
"num" => "19",
"minPrice" => "456600.00",
"invoice" => "1",
"goodsType" => "2",
"salestate" => "",
"price" => "30.50",
"autoName" => "{"brandName":"奔驰","subBrandName":"奔驰(进口)","serieName":"奔驰B级","autoName":"2015-B 200 豪华型"}",
"fullPayOn" => "1",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "2015-B 200 豪华型",
"stockType" => "2",
"finalTimeWap" => "2015-07-31 14:30:00",
"serieName" => "奔驰(进口) 奔驰B级 B 200 豪华型",
"images" => array
(
"0" => array
(
"id" => "914",
"gid" => "1163",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/iqgu.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114964",
),
"1" => array
(
"id" => "915",
"gid" => "1163",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/ofrt.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114964",
),
"2" => array
(
"id" => "916",
"gid" => "1163",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/gzwg.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114964",
),
"3" => array
(
"id" => "917",
"gid" => "1163",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/dtat.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437114964",
),
"4" => array
(
"id" => "918",
"gid" => "1163",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/exii.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "2",
"insertTime" => "1437114964",
),
),
),
"dealer" => array
(
"23202" => array
(
"dealerid" => "23202",
"name" => "G商城测试商户A",
"member" => "4S店",
"linkName" => "测试任君生",
"linkPhone" => "15810722228",
"telephone" => "15810722228",
"address" => "北京北京",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.445192",
"latitude" => "39.928740",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"2" => array
(
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "2",
"subBrand" => array
(
"2" => array
(
"id" => "2",
"subBrandName" => "一汽奥迪",
"sub_brandid" => "2",
),
),
),
"5" => array
(
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "5",
"subBrand" => array
(
"7" => array
(
"id" => "7",
"subBrandName" => "华晨宝马",
"sub_brandid" => "7",
),
"9" => array
(
"id" => "9",
"subBrandName" => "宝马M",
"sub_brandid" => "9",
),
),
),
"8" => array
(
"brandName" => "奔驰",
"logo" => "http://img.emao.net/car/logo/nd/bah/hboc.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "8",
"subBrand" => array
(
"12" => array
(
"id" => "12",
"subBrandName" => "北京奔驰",
"sub_brandid" => "12",
),
"13" => array
(
"id" => "13",
"subBrandName" => "福建奔驰",
"sub_brandid" => "13",
),
"15" => array
(
"id" => "15",
"subBrandName" => "奔驰AMG",
"sub_brandid" => "15",
),
"204" => array
(
"id" => "204",
"subBrandName" => "奔驰-迈巴赫",
"sub_brandid" => "204",
),
),
),
),
),
),
"invoice" => array
(
"name" => "抵扣券6000不允许使用券",
"phone" => "13718863804",
"VIN" => "",
"price" => "305000.00",
),
"ticketInfo" => array
(
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
"2" => array
(
"id" => "1114",
"orderId" => "215071731155766154653",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1162",
"colorId" => "6",
"colorName" => "大红色",
"brandId" => "8",
"subBrandId" => "12",
"serieId" => "1532",
"autoId" => "13183",
"userName" => "抵扣券5000线上2000线下30002",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23202",
"pointId" => "23202",
"price" => "0.00",
"emaoPrice" => "398000.00",
"couponValue" => "5000.00",
"gType" => "1",
"insertTime" => "2015-07-17 19:05:55",
"cancelTime" => "0",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "",
"payType" => "",
"payTime" => "0",
"payTradeNo" => "",
"state" => "2",
"gift" => array
(
"id" => "31",
"type" => "1",
"cover" => "/mall/nd/bal/gxya.jpg",
"name" => "100元加油卡",
"price" => "100.00",
"descr" => "赠品描述：全额即送100元加油卡",
"addTime" => "1432792213",
"addUser" => "liqiaoxia381@emao.com",
"state" => "1",
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "429899606903",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "",
"deposit" => "0.00",
"couponSellPrice" => "0.03",
"offlinePrice" => "393000",
"offlineReduce" => "11000.00",
"goods" => array
(
"id" => "1162",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "8",
"subBrandId" => "12",
"serieId" => "1532",
"autoId" => "13183",
"smsTitle" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1437114631",
"updateTime" => "1437115021",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1437114652",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1437114656",
"backTime" => "",
"preSellTime" => "1437114600",
"sellTime" => "1437114600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439015400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "88",
"sortState" => "88",
"description" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1438322400",
"sellLead" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张",
"num" => "4",
"minPrice" => "348900.00",
"invoice" => "1",
"goodsType" => "2",
"salestate" => "",
"price" => "39.80",
"autoName" => "{"brandName":"奔驰","subBrandName":"北京奔驰","serieName":"奔驰GLA级","autoName":"2015-260 4MATIC 运动型"}",
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "3",
"goodsName" => "2015-260 4MATIC 运动型",
"stockType" => "1",
"finalTimeWap" => "2015-07-31 14:00:00",
"serieName" => "北京奔驰 奔驰GLA级 260 4MATIC 运动型",
"images" => array
(
"0" => array
(
"id" => "909",
"gid" => "1162",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/cuux.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"1" => array
(
"id" => "910",
"gid" => "1162",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/dmzk.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"2" => array
(
"id" => "911",
"gid" => "1162",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/sgz.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"3" => array
(
"id" => "912",
"gid" => "1162",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/nzqg.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437114632",
),
"4" => array
(
"id" => "913",
"gid" => "1162",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/lrax.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "2",
"insertTime" => "1437114632",
),
),
),
"dealer" => array
(
"23202" => array
(
"dealerid" => "23202",
"name" => "G商城测试商户A",
"member" => "4S店",
"linkName" => "测试任君生",
"linkPhone" => "15810722228",
"telephone" => "15810722228",
"address" => "北京北京",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.445192",
"latitude" => "39.928740",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"2" => array
(
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "2",
"subBrand" => array
(
"2" => array
(
"id" => "2",
"subBrandName" => "一汽奥迪",
"sub_brandid" => "2",
),
),
),
"5" => array
(
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "5",
"subBrand" => array
(
"7" => array
(
"id" => "7",
"subBrandName" => "华晨宝马",
"sub_brandid" => "7",
),
"9" => array
(
"id" => "9",
"subBrandName" => "宝马M",
"sub_brandid" => "9",
),
),
),
"8" => array
(
"brandName" => "奔驰",
"logo" => "http://img.emao.net/car/logo/nd/bah/hboc.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "8",
"subBrand" => array
(
"12" => array
(
"id" => "12",
"subBrandName" => "北京奔驰",
"sub_brandid" => "12",
),
"13" => array
(
"id" => "13",
"subBrandName" => "福建奔驰",
"sub_brandid" => "13",
),
"15" => array
(
"id" => "15",
"subBrandName" => "奔驰AMG",
"sub_brandid" => "15",
),
"204" => array
(
"id" => "204",
"subBrandName" => "奔驰-迈巴赫",
"sub_brandid" => "204",
),
),
),
),
),
),
"invoice" => array
(
"name" => "抵扣券5000线上2000线下30002",
"phone" => "13718863804",
"VIN" => "",
"price" => "398000.00",
),
"ticketInfo" => array
(
"ticketInfo" => array
(
"709" => array
(
"id" => "709",
"sn" => "4SGM92TZR5VXAPEN",
"batchId" => "34",
"userId" => "35744",
"orderId" => "215071731155766154653",
"cancel" => "2",
"useScene" => "1",
"price" => "2000.00",
),
"728" => array
(
"id" => "728",
"sn" => "Y7M861RSK20TOBGQ",
"batchId" => "35",
"userId" => "35744",
"orderId" => "215071731155766154653",
"cancel" => "2",
"useScene" => "2",
"price" => "3000.00",
),
"729" => array
(
"id" => "729",
"sn" => "402XDUKZS9C3HQTR",
"batchId" => "35",
"userId" => "35744",
"orderId" => "215071731155766154653",
"cancel" => "2",
"useScene" => "2",
"price" => "3000.00",
),
),
"ticketInfoRes" => array
(
"allnum" => "3",
"onlinenum" => "1",
"onlinePay" => "2000",
"offlinenum" => "2",
"offlinePay" => "6000",
),
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
"3" => array
(
"id" => "1113",
"orderId" => "215071730605093870855",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1162",
"colorId" => "6",
"colorName" => "大红色",
"brandId" => "8",
"subBrandId" => "12",
"serieId" => "1532",
"autoId" => "13183",
"userName" => "抵扣券线下3000",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23202",
"pointId" => "23202",
"price" => "0.03",
"emaoPrice" => "398000.00",
"couponValue" => "5000.00",
"gType" => "1",
"insertTime" => "2015-07-17 18:56:45",
"cancelTime" => "0",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "13718863804",
"payType" => "1",
"payTime" => "1437373004",
"payTradeNo" => "2015072000001000810060148749",
"state" => "2",
"gift" => array
(
"id" => "31",
"type" => "1",
"cover" => "/mall/nd/bal/gxya.jpg",
"name" => "100元加油卡",
"price" => "100.00",
"descr" => "赠品描述：全额即送100元加油卡",
"addTime" => "1432792213",
"addUser" => "liqiaoxia381@emao.com",
"state" => "1",
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "429051639551",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "21507173060509387085565",
"deposit" => "0.00",
"couponSellPrice" => "0.03",
"offlinePrice" => "393000",
"offlineReduce" => "8000.00",
"goods" => array
(
"id" => "1162",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "8",
"subBrandId" => "12",
"serieId" => "1532",
"autoId" => "13183",
"smsTitle" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1437114631",
"updateTime" => "1437115021",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1437114652",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1437114656",
"backTime" => "",
"preSellTime" => "1437114600",
"sellTime" => "1437114600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439015400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "88",
"sortState" => "88",
"description" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1438322400",
"sellLead" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张",
"num" => "4",
"minPrice" => "348900.00",
"invoice" => "1",
"goodsType" => "2",
"salestate" => "",
"price" => "39.80",
"autoName" => "{"brandName":"奔驰","subBrandName":"北京奔驰","serieName":"奔驰GLA级","autoName":"2015-260 4MATIC 运动型"}",
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "3",
"goodsName" => "2015-260 4MATIC 运动型",
"stockType" => "1",
"finalTimeWap" => "2015-07-31 14:00:00",
"serieName" => "北京奔驰 奔驰GLA级 260 4MATIC 运动型",
"images" => array
(
"0" => array
(
"id" => "909",
"gid" => "1162",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/cuux.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"1" => array
(
"id" => "910",
"gid" => "1162",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/dmzk.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"2" => array
(
"id" => "911",
"gid" => "1162",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/sgz.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"3" => array
(
"id" => "912",
"gid" => "1162",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/nzqg.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437114632",
),
"4" => array
(
"id" => "913",
"gid" => "1162",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/lrax.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "2",
"insertTime" => "1437114632",
),
),
),
"dealer" => array
(
"23202" => array
(
"dealerid" => "23202",
"name" => "G商城测试商户A",
"member" => "4S店",
"linkName" => "测试任君生",
"linkPhone" => "15810722228",
"telephone" => "15810722228",
"address" => "北京北京",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.445192",
"latitude" => "39.928740",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"2" => array
(
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "2",
"subBrand" => array
(
"2" => array
(
"id" => "2",
"subBrandName" => "一汽奥迪",
"sub_brandid" => "2",
),
),
),
"5" => array
(
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "5",
"subBrand" => array
(
"7" => array
(
"id" => "7",
"subBrandName" => "华晨宝马",
"sub_brandid" => "7",
),
"9" => array
(
"id" => "9",
"subBrandName" => "宝马M",
"sub_brandid" => "9",
),
),
),
"8" => array
(
"brandName" => "奔驰",
"logo" => "http://img.emao.net/car/logo/nd/bah/hboc.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "8",
"subBrand" => array
(
"12" => array
(
"id" => "12",
"subBrandName" => "北京奔驰",
"sub_brandid" => "12",
),
"13" => array
(
"id" => "13",
"subBrandName" => "福建奔驰",
"sub_brandid" => "13",
),
"15" => array
(
"id" => "15",
"subBrandName" => "奔驰AMG",
"sub_brandid" => "15",
),
"204" => array
(
"id" => "204",
"subBrandName" => "奔驰-迈巴赫",
"sub_brandid" => "204",
),
),
),
),
),
),
"invoice" => array
(
"name" => "抵扣券线下3000",
"phone" => "13718863804",
"VIN" => "",
"price" => "398000.00",
),
"ticketInfo" => array
(
"ticketInfo" => array
(
"727" => array
(
"id" => "727",
"sn" => "A2JWVDSL7QRIT40K",
"batchId" => "35",
"userId" => "35744",
"orderId" => "215071730605093870855",
"cancel" => "2",
"useScene" => "2",
"price" => "3000.00",
),
),
"ticketInfoRes" => array
(
"allnum" => "1",
"onlinenum" => "",
"onlinePay" => "",
"offlinenum" => "1",
"offlinePay" => "3000",
),
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
"4" => array
(
"id" => "1112",
"orderId" => "215071730462295531926",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1162",
"colorId" => "6",
"colorName" => "大红色",
"brandId" => "8",
"subBrandId" => "12",
"serieId" => "1532",
"autoId" => "13183",
"userName" => "抵扣券5000线上2000券",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23202",
"pointId" => "23202",
"price" => "0.00",
"emaoPrice" => "398000.00",
"couponValue" => "5000.00",
"gType" => "1",
"insertTime" => "2015-07-17 18:54:22",
"cancelTime" => "0",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "",
"payType" => "",
"payTime" => "0",
"payTradeNo" => "",
"state" => "1",
"gift" => array
(
"id" => "31",
"type" => "1",
"cover" => "/mall/nd/bal/gxya.jpg",
"name" => "100元加油卡",
"price" => "100.00",
"descr" => "赠品描述：全额即送100元加油卡",
"addTime" => "1432792213",
"addUser" => "liqiaoxia381@emao.com",
"state" => "1",
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "0",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "",
"deposit" => "0.00",
"couponSellPrice" => "0.03",
"offlinePrice" => "393000",
"offlineReduce" => "5000.00",
"goods" => array
(
"id" => "1162",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "8",
"subBrandId" => "12",
"serieId" => "1532",
"autoId" => "13183",
"smsTitle" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1437114631",
"updateTime" => "1437115021",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1437114652",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1437114656",
"backTime" => "",
"preSellTime" => "1437114600",
"sellTime" => "1437114600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439015400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "88",
"sortState" => "88",
"description" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1438322400",
"sellLead" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张",
"num" => "4",
"minPrice" => "348900.00",
"invoice" => "1",
"goodsType" => "2",
"salestate" => "",
"price" => "39.80",
"autoName" => "{"brandName":"奔驰","subBrandName":"北京奔驰","serieName":"奔驰GLA级","autoName":"2015-260 4MATIC 运动型"}",
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "3",
"goodsName" => "2015-260 4MATIC 运动型",
"stockType" => "1",
"finalTimeWap" => "2015-07-31 14:00:00",
"serieName" => "北京奔驰 奔驰GLA级 260 4MATIC 运动型",
"images" => array
(
"0" => array
(
"id" => "909",
"gid" => "1162",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/cuux.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"1" => array
(
"id" => "910",
"gid" => "1162",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/dmzk.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"2" => array
(
"id" => "911",
"gid" => "1162",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/sgz.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"3" => array
(
"id" => "912",
"gid" => "1162",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/nzqg.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437114632",
),
"4" => array
(
"id" => "913",
"gid" => "1162",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/lrax.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "2",
"insertTime" => "1437114632",
),
),
),
"dealer" => array
(
"23202" => array
(
"dealerid" => "23202",
"name" => "G商城测试商户A",
"member" => "4S店",
"linkName" => "测试任君生",
"linkPhone" => "15810722228",
"telephone" => "15810722228",
"address" => "北京北京",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.445192",
"latitude" => "39.928740",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"2" => array
(
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "2",
"subBrand" => array
(
"2" => array
(
"id" => "2",
"subBrandName" => "一汽奥迪",
"sub_brandid" => "2",
),
),
),
"5" => array
(
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "5",
"subBrand" => array
(
"7" => array
(
"id" => "7",
"subBrandName" => "华晨宝马",
"sub_brandid" => "7",
),
"9" => array
(
"id" => "9",
"subBrandName" => "宝马M",
"sub_brandid" => "9",
),
),
),
"8" => array
(
"brandName" => "奔驰",
"logo" => "http://img.emao.net/car/logo/nd/bah/hboc.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "8",
"subBrand" => array
(
"12" => array
(
"id" => "12",
"subBrandName" => "北京奔驰",
"sub_brandid" => "12",
),
"13" => array
(
"id" => "13",
"subBrandName" => "福建奔驰",
"sub_brandid" => "13",
),
"15" => array
(
"id" => "15",
"subBrandName" => "奔驰AMG",
"sub_brandid" => "15",
),
"204" => array
(
"id" => "204",
"subBrandName" => "奔驰-迈巴赫",
"sub_brandid" => "204",
),
),
),
),
),
),
"invoice" => array
(
"name" => "抵扣券5000线上2000券",
"phone" => "13718863804",
"VIN" => "",
"price" => "398000.00",
),
"ticketInfo" => array
(
"ticketInfo" => array
(
"708" => array
(
"id" => "708",
"sn" => "2Q60UP8YAR5FEWKS",
"batchId" => "34",
"userId" => "35744",
"orderId" => "215071730462295531926",
"cancel" => "2",
"useScene" => "1",
"price" => "2000.00",
),
),
"ticketInfoRes" => array
(
"allnum" => "1",
"onlinenum" => "1",
"onlinePay" => "2000",
"offlinenum" => "",
"offlinePay" => "",
),
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
"5" => array
(
"id" => "1111",
"orderId" => "215071730289177994857",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1162",
"colorId" => "6",
"colorName" => "大红色",
"brandId" => "8",
"subBrandId" => "12",
"serieId" => "1532",
"autoId" => "13183",
"userName" => "抵扣券允许使用券但是不用",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23202",
"pointId" => "23202",
"price" => "0.03",
"emaoPrice" => "398000.00",
"couponValue" => "5000.00",
"gType" => "1",
"insertTime" => "2015-07-17 18:51:29",
"cancelTime" => "0",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "",
"payType" => "",
"payTime" => "0",
"payTradeNo" => "",
"state" => "1",
"gift" => array
(
"id" => "31",
"type" => "1",
"cover" => "/mall/nd/bal/gxya.jpg",
"name" => "100元加油卡",
"price" => "100.00",
"descr" => "赠品描述：全额即送100元加油卡",
"addTime" => "1432792213",
"addUser" => "liqiaoxia381@emao.com",
"state" => "1",
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "0",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "",
"deposit" => "0.00",
"couponSellPrice" => "0.03",
"offlinePrice" => "393000",
"offlineReduce" => "5000.00",
"goods" => array
(
"id" => "1162",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "8",
"subBrandId" => "12",
"serieId" => "1532",
"autoId" => "13183",
"smsTitle" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p>自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张</p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liukang317@emao.com",
"insertTime" => "1437114631",
"updateTime" => "1437115021",
"submitUser" => "liukang317@emao.com",
"submitTime" => "1437114652",
"checkUser" => "liukang317@emao.com",
"checkTime" => "1437114656",
"backTime" => "",
"preSellTime" => "1437114600",
"sellTime" => "1437114600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439015400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "88",
"sortState" => "88",
"description" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1438322400",
"sellLead" => "自采，限时抢购，抵扣券，必须上传，显示库存，允许使用优惠券3张",
"num" => "4",
"minPrice" => "348900.00",
"invoice" => "1",
"goodsType" => "2",
"salestate" => "",
"price" => "39.80",
"autoName" => "{"brandName":"奔驰","subBrandName":"北京奔驰","serieName":"奔驰GLA级","autoName":"2015-260 4MATIC 运动型"}",
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "3",
"goodsName" => "2015-260 4MATIC 运动型",
"stockType" => "1",
"finalTimeWap" => "2015-07-31 14:00:00",
"serieName" => "北京奔驰 奔驰GLA级 260 4MATIC 运动型",
"images" => array
(
"0" => array
(
"id" => "909",
"gid" => "1162",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/cuux.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"1" => array
(
"id" => "910",
"gid" => "1162",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/dmzk.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"2" => array
(
"id" => "911",
"gid" => "1162",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/sgz.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437114632",
),
"3" => array
(
"id" => "912",
"gid" => "1162",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/nzqg.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437114632",
),
"4" => array
(
"id" => "913",
"gid" => "1162",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/lrax.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "2",
"insertTime" => "1437114632",
),
),
),
"dealer" => array
(
"23202" => array
(
"dealerid" => "23202",
"name" => "G商城测试商户A",
"member" => "4S店",
"linkName" => "测试任君生",
"linkPhone" => "15810722228",
"telephone" => "15810722228",
"address" => "北京北京",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.445192",
"latitude" => "39.928740",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"2" => array
(
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "2",
"subBrand" => array
(
"2" => array
(
"id" => "2",
"subBrandName" => "一汽奥迪",
"sub_brandid" => "2",
),
),
),
"5" => array
(
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "5",
"subBrand" => array
(
"7" => array
(
"id" => "7",
"subBrandName" => "华晨宝马",
"sub_brandid" => "7",
),
"9" => array
(
"id" => "9",
"subBrandName" => "宝马M",
"sub_brandid" => "9",
),
),
),
"8" => array
(
"brandName" => "奔驰",
"logo" => "http://img.emao.net/car/logo/nd/bah/hboc.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "8",
"subBrand" => array
(
"12" => array
(
"id" => "12",
"subBrandName" => "北京奔驰",
"sub_brandid" => "12",
),
"13" => array
(
"id" => "13",
"subBrandName" => "福建奔驰",
"sub_brandid" => "13",
),
"15" => array
(
"id" => "15",
"subBrandName" => "奔驰AMG",
"sub_brandid" => "15",
),
"204" => array
(
"id" => "204",
"subBrandName" => "奔驰-迈巴赫",
"sub_brandid" => "204",
),
),
),
),
),
),
"invoice" => array
(
"name" => "抵扣券允许使用券但是不用",
"phone" => "13718863804",
"VIN" => "",
"price" => "398000.00",
),
"ticketInfo" => array
(
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
"6" => array
(
"id" => "1110",
"orderId" => "215071729945353273180",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1167",
"colorId" => "1",
"colorName" => "亚光黑",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "1",
"userName" => "全款有优惠不允许使用券",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23212",
"pointId" => "23202",
"price" => "119000.00",
"emaoPrice" => "120000.00",
"couponValue" => "1000.00",
"gType" => "3",
"insertTime" => "2015-07-17 18:45:45",
"cancelTime" => "0",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "",
"payType" => "",
"payTime" => "0",
"payTradeNo" => "",
"state" => "1",
"gift" => array
(
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "0",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "",
"deposit" => "0.00",
"couponSellPrice" => "0.00",
"offlinePrice" => "0",
"offlineReduce" => "",
"goods" => array
(
"id" => "1167",
"consumerId" => "23212",
"sellType" => "4",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "1",
"smsTitle" => "全款有优惠不允许使用优惠券",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p><br/></p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1437129795",
"updateTime" => "1437129893",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1437129812",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1437129819",
"backTime" => "",
"preSellTime" => "1437129000",
"sellTime" => "1437129000",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441276200",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "3",
"sortState" => "3",
"description" => "全款有优惠不允许使用优惠券",
"isRefund" => "1",
"discountWay" => "1",
"discount" => "1000.00",
"contractNo" => "",
"finalTime" => "1439029800",
"sellLead" => "全款有优惠不允许使用优惠券",
"num" => "59",
"minPrice" => "120000.00",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "368.80",
"autoName" => "{"brandName":"阿斯顿·马丁","subBrandName":"阿斯顿·马丁","serieName":"Rapide","autoName":"2010-6.0L V11"}",
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "0",
"goodsName" => "2010-6.0L V11",
"stockType" => "1",
"finalTimeWap" => "2015-08-08 18:30:00",
"serieName" => "阿斯顿·马丁 Rapide 6.0L V11",
"images" => array
(
"0" => array
(
"id" => "944",
"gid" => "1167",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/kswq.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437129795",
),
"1" => array
(
"id" => "945",
"gid" => "1167",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/orwv.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437129795",
),
"2" => array
(
"id" => "946",
"gid" => "1167",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/bkny.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437129795",
),
"3" => array
(
"id" => "947",
"gid" => "1167",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/ikid.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437129795",
),
),
),
"dealer" => array
(
"23202" => array
(
"dealerid" => "23202",
"name" => "G商城测试商户A",
"member" => "4S店",
"linkName" => "测试任君生",
"linkPhone" => "15810722228",
"telephone" => "15810722228",
"address" => "北京北京",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.445192",
"latitude" => "39.928740",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"2" => array
(
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "2",
"subBrand" => array
(
"2" => array
(
"id" => "2",
"subBrandName" => "一汽奥迪",
"sub_brandid" => "2",
),
),
),
"5" => array
(
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "5",
"subBrand" => array
(
"7" => array
(
"id" => "7",
"subBrandName" => "华晨宝马",
"sub_brandid" => "7",
),
"9" => array
(
"id" => "9",
"subBrandName" => "宝马M",
"sub_brandid" => "9",
),
),
),
"8" => array
(
"brandName" => "奔驰",
"logo" => "http://img.emao.net/car/logo/nd/bah/hboc.png",
"firstWord" => "B",
"state" => "1",
"brandid" => "8",
"subBrand" => array
(
"12" => array
(
"id" => "12",
"subBrandName" => "北京奔驰",
"sub_brandid" => "12",
),
"13" => array
(
"id" => "13",
"subBrandName" => "福建奔驰",
"sub_brandid" => "13",
),
"15" => array
(
"id" => "15",
"subBrandName" => "奔驰AMG",
"sub_brandid" => "15",
),
"204" => array
(
"id" => "204",
"subBrandName" => "奔驰-迈巴赫",
"sub_brandid" => "204",
),
),
),
),
),
),
"invoice" => array
(
"name" => "全款有优惠不允许使用券",
"phone" => "13718863804",
"VIN" => "",
"price" => "120000.00",
),
"ticketInfo" => array
(
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
"7" => array
(
"id" => "1107",
"orderId" => "215071729445735847478",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1161",
"colorId" => "11",
"colorName" => "绿色",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"userName" => "整车意向金线上20002线下3000",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23202",
"pointId" => "23212",
"price" => "0.00",
"emaoPrice" => "1650000.00",
"couponValue" => "0.00",
"gType" => "2",
"insertTime" => "2015-07-17 18:37:25",
"cancelTime" => "0",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "",
"payType" => "",
"payTime" => "0",
"payTradeNo" => "",
"state" => "1",
"gift" => array
(
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "0",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "",
"deposit" => "0.03",
"couponSellPrice" => "0.00",
"offlinePrice" => "1650000",
"offlineReduce" => "",
"goods" => array
(
"id" => "1161",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"smsTitle" => "意向金允许使用优惠券",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p><br/></p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1437114402",
"updateTime" => "1437116011",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1437115865",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1437115984",
"backTime" => "",
"preSellTime" => "1437114600",
"sellTime" => "1437114600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439015400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "604",
"sortState" => "604",
"description" => "意向金允许使用优惠券",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1439015400",
"sellLead" => "意向金允许使用优惠券、全款无优惠",
"num" => "81",
"minPrice" => "1650000.00",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "27.30",
"autoName" => "{"brandName":"奥迪","subBrandName":"一汽奥迪","serieName":"奥迪A4L","autoName":"1.8 TFSI 手动舒适型"}",
"fullPayOn" => "1",
"isPurchase" => "0",
"ticketCount" => "3",
"goodsName" => "2012-1.8 TFSI 手动舒适型",
"stockType" => "1",
"finalTimeWap" => "2015-08-08 14:30:00",
"serieName" => "一汽奥迪 奥迪A4L 1.8 TFSI 手动舒适型",
"images" => array
(
"0" => array
(
"id" => "905",
"gid" => "1161",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/fpne.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437115030",
),
"1" => array
(
"id" => "906",
"gid" => "1161",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/dgxv.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437115030",
),
"2" => array
(
"id" => "907",
"gid" => "1161",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/fvoq.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437115030",
),
"3" => array
(
"id" => "908",
"gid" => "1161",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/dzcj.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437115030",
),
),
),
"dealer" => array
(
"23212" => array
(
"dealerid" => "23212",
"name" => "专用的经销商勿动",
"member" => "4S店",
"linkName" => "李巧霞",
"linkPhone" => "13718863804",
"telephone" => "0101234567",
"address" => "方正大厦",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.319640",
"latitude" => "39.990450",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"1" => array
(
"brandName" => "阿斯顿·马丁",
"logo" => "http://img.emao.net/car/logo/nd/bah/oxp.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "1",
"subBrand" => array
(
"1" => array
(
"id" => "1",
"subBrandName" => "阿斯顿·马丁",
"sub_brandid" => "1",
),
),
),
),
),
),
"invoice" => array
(
"name" => "整车意向金线上20002线下3000",
"phone" => "13718863804",
"VIN" => "",
"price" => "1650000.00",
),
"ticketInfo" => array
(
"ticketInfo" => array
(
"706" => array
(
"id" => "706",
"sn" => "9IMUXHF84QT7CVSY",
"batchId" => "34",
"userId" => "35744",
"orderId" => "215071729445735847478",
"cancel" => "2",
"useScene" => "1",
"price" => "2000.00",
),
"707" => array
(
"id" => "707",
"sn" => "XAIZER6SNTY23CBK",
"batchId" => "34",
"userId" => "35744",
"orderId" => "215071729445735847478",
"cancel" => "2",
"useScene" => "1",
"price" => "2000.00",
),
"726" => array
(
"id" => "726",
"sn" => "LFSNAYKJU05IQC8D",
"batchId" => "35",
"userId" => "35744",
"orderId" => "215071729445735847478",
"cancel" => "2",
"useScene" => "2",
"price" => "3000.00",
),
),
"ticketInfoRes" => array
(
"allnum" => "3",
"onlinenum" => "2",
"onlinePay" => "4000",
"offlinenum" => "1",
"offlinePay" => "3000",
),
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
"8" => array
(
"id" => "1106",
"orderId" => "215071729166896294689",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1161",
"colorId" => "11",
"colorName" => "绿色",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"userName" => "整车意向金允许使用券-线上2000",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23202",
"pointId" => "23212",
"price" => "0.00",
"emaoPrice" => "1650000.00",
"couponValue" => "0.00",
"gType" => "2",
"insertTime" => "2015-07-17 18:32:46",
"cancelTime" => "0",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "",
"payType" => "",
"payTime" => "0",
"payTradeNo" => "",
"state" => "1",
"gift" => array
(
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "0",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "",
"deposit" => "0.03",
"couponSellPrice" => "0.00",
"offlinePrice" => "1650000",
"offlineReduce" => "",
"goods" => array
(
"id" => "1161",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"smsTitle" => "意向金允许使用优惠券",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p><br/></p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1437114402",
"updateTime" => "1437116011",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1437115865",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1437115984",
"backTime" => "",
"preSellTime" => "1437114600",
"sellTime" => "1437114600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439015400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "604",
"sortState" => "604",
"description" => "意向金允许使用优惠券",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1439015400",
"sellLead" => "意向金允许使用优惠券、全款无优惠",
"num" => "81",
"minPrice" => "1650000.00",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "27.30",
"autoName" => "{"brandName":"奥迪","subBrandName":"一汽奥迪","serieName":"奥迪A4L","autoName":"1.8 TFSI 手动舒适型"}",
"fullPayOn" => "1",
"isPurchase" => "0",
"ticketCount" => "3",
"goodsName" => "2012-1.8 TFSI 手动舒适型",
"stockType" => "1",
"finalTimeWap" => "2015-08-08 14:30:00",
"serieName" => "一汽奥迪 奥迪A4L 1.8 TFSI 手动舒适型",
"images" => array
(
"0" => array
(
"id" => "905",
"gid" => "1161",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/fpne.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437115030",
),
"1" => array
(
"id" => "906",
"gid" => "1161",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/dgxv.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437115030",
),
"2" => array
(
"id" => "907",
"gid" => "1161",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/fvoq.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437115030",
),
"3" => array
(
"id" => "908",
"gid" => "1161",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/dzcj.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437115030",
),
),
),
"dealer" => array
(
"23212" => array
(
"dealerid" => "23212",
"name" => "专用的经销商勿动",
"member" => "4S店",
"linkName" => "李巧霞",
"linkPhone" => "13718863804",
"telephone" => "0101234567",
"address" => "方正大厦",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.319640",
"latitude" => "39.990450",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"1" => array
(
"brandName" => "阿斯顿·马丁",
"logo" => "http://img.emao.net/car/logo/nd/bah/oxp.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "1",
"subBrand" => array
(
"1" => array
(
"id" => "1",
"subBrandName" => "阿斯顿·马丁",
"sub_brandid" => "1",
),
),
),
),
),
),
"invoice" => array
(
"name" => "整车意向金允许使用券-线上2000",
"phone" => "13718863804",
"VIN" => "",
"price" => "1650000.00",
),
"ticketInfo" => array
(
"ticketInfo" => array
(
"705" => array
(
"id" => "705",
"sn" => "GCS86TDXVMJZU7KW",
"batchId" => "34",
"userId" => "35744",
"orderId" => "215071729166896294689",
"cancel" => "2",
"useScene" => "1",
"price" => "2000.00",
),
),
"ticketInfoRes" => array
(
"allnum" => "1",
"onlinenum" => "1",
"onlinePay" => "2000",
"offlinenum" => "",
"offlinePay" => "",
),
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
"9" => array
(
"id" => "1105",
"orderId" => "215071729075088112682",
"userId" => "35744",
"userIp" => "192.168.20.155",
"gId" => "1161",
"colorId" => "11",
"colorName" => "绿色",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"userName" => "整车意向金允许使用券-线上2000",
"phone" => "13718863804",
"idCard" => "422826197804060543",
"consumerId" => "23202",
"pointId" => "23212",
"price" => "0.03",
"emaoPrice" => "1650000.00",
"couponValue" => "0.00",
"gType" => "2",
"insertTime" => "2015-07-17 18:31:15",
"cancelTime" => "1437129106",
"refundTime" => "0",
"financeTime" => "0",
"takeTime" => "0",
"payAccount" => "",
"payType" => "",
"payTime" => "0",
"payTradeNo" => "",
"state" => "3",
"gift" => array
(
),
"isFrozen" => "1",
"frozenUser" => "",
"frozenTime" => "0",
"unFrozenUser" => "",
"unFrozenTime" => "0",
"code" => "0",
"codeState" => "1",
"codeVarifyTime" => "0",
"payOrderNo" => "",
"deposit" => "0.03",
"couponSellPrice" => "0.00",
"offlinePrice" => "1649999.97",
"offlineReduce" => "",
"goods" => array
(
"id" => "1161",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "28",
"smsTitle" => "意向金允许使用优惠券",
"pcContent" => "<div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">推荐理由</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">活动说明</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">购买须知</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">车型详情</div></div><div class="detail-con-box"><p><br/></p></div><div class="detail-class" style="height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;"><div class="class-item" style="position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; ">免责声明</div></div><div class="detail-con-box"><p><br/></p></div>",
"mContent" => "<div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">推荐理由</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">活动说明</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">购买须知</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">车型详情</div></div><div class="detail-nei"><p><br/></p></div><div class="detail-item" style="border-bottom:#dcd7d7 solid 2px; width: 100%; height: 20px; line-height: 20px; margin-top: 10px; font-size:11px;position: relative;"><div class="detail-item-nav" style="border-bottom:#df3b58 solid 2px; padding:0 11px; position: absolute;">免责声明</div></div><div class="detail-nei"><p><br/></p></div>",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1437114402",
"updateTime" => "1437116011",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1437115865",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1437115984",
"backTime" => "",
"preSellTime" => "1437114600",
"sellTime" => "1437114600",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439015400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "604",
"sortState" => "604",
"description" => "意向金允许使用优惠券",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0.00",
"contractNo" => "",
"finalTime" => "1439015400",
"sellLead" => "意向金允许使用优惠券、全款无优惠",
"num" => "81",
"minPrice" => "1650000.00",
"invoice" => "1",
"goodsType" => "1",
"salestate" => "",
"price" => "27.30",
"autoName" => "{"brandName":"奥迪","subBrandName":"一汽奥迪","serieName":"奥迪A4L","autoName":"1.8 TFSI 手动舒适型"}",
"fullPayOn" => "1",
"isPurchase" => "0",
"ticketCount" => "3",
"goodsName" => "2012-1.8 TFSI 手动舒适型",
"stockType" => "1",
"finalTimeWap" => "2015-08-08 14:30:00",
"serieName" => "一汽奥迪 奥迪A4L 1.8 TFSI 手动舒适型",
"images" => array
(
"0" => array
(
"id" => "905",
"gid" => "1161",
"imgIndex" => "0",
"image" => "http://img.emao.net/mall/nd/bal/fpne.jpg",
"type" => "1",
"isMain" => "1",
"platform" => "1",
"insertTime" => "1437115030",
),
"1" => array
(
"id" => "906",
"gid" => "1161",
"imgIndex" => "1",
"image" => "http://img.emao.net/mall/nd/bal/dgxv.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437115030",
),
"2" => array
(
"id" => "907",
"gid" => "1161",
"imgIndex" => "3",
"image" => "http://img.emao.net/mall/nd/bal/fvoq.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437115030",
),
"3" => array
(
"id" => "908",
"gid" => "1161",
"imgIndex" => "2",
"image" => "http://img.emao.net/mall/nd/bal/dzcj.jpg",
"type" => "1",
"isMain" => "0",
"platform" => "1",
"insertTime" => "1437115030",
),
),
),
"dealer" => array
(
"23212" => array
(
"dealerid" => "23212",
"name" => "专用的经销商勿动",
"member" => "4S店",
"linkName" => "李巧霞",
"linkPhone" => "13718863804",
"telephone" => "0101234567",
"address" => "方正大厦",
"provinceId" => "1",
"cityId" => "1",
"longitude" => "116.319640",
"latitude" => "39.990450",
"isdel" => "0",
"istest" => "0",
"province" => "北京",
"city" => "北京",
"brand" => array
(
"1" => array
(
"brandName" => "阿斯顿·马丁",
"logo" => "http://img.emao.net/car/logo/nd/bah/oxp.png",
"firstWord" => "A",
"state" => "1",
"brandid" => "1",
"subBrand" => array
(
"1" => array
(
"id" => "1",
"subBrandName" => "阿斯顿·马丁",
"sub_brandid" => "1",
),
),
),
),
),
),
"invoice" => array
(
"name" => "整车意向金允许使用券-线上2000",
"phone" => "13718863804",
"VIN" => "",
"price" => "1650000.00",
),
"ticketInfo" => array
(
),
"mainImage" => "http://img.emao.net/car/test.jpg/31",
),
),
"currPage" => "1",
"size" => "10",
"count" => "23",
"order_cancel_limit" => "4320",
),
),
"pageTitle" => "我的订单_特卖商城_一猫汽车商城",
"pageKeyword" => "特卖商城,一猫汽车商城",
"pageDescription" => "我在一猫特卖商城中的订单",
"__loginInfo" => array
(
"id" => "35744",
"username" => "youhuiquan",
"nickname" => "youhuiquan",
"realname" => "",
"pwd" => "46f94c8de14fb36680850768ff1b7f2a",
"birthday" => "",
"sex" => "-1",
"selfintro" => "",
"phone" => "",
"phoneValid" => "",
"mail" => "",
"mailValid" => "",
"nation_id" => "0",
"province_id" => "0",
"city_id" => "0",
"district_id" => "0",
"major" => "",
"mood" => "",
"tags" => "",
"head_img_uri" => "http://s.emao.net/images/common/uc_user_avatar.png",
"role" => "0",
"regIP" => "192.168.20.196",
"login_time" => "2015-07-20 16:08:37",
"reg_time" => "2015-07-17 11:58:33",
"update_time" => "2015-07-20 16:08:37",
"completeStatus" => "5",
"status" => "1",
"source" => "0",
"client" => "1",
"auditStatus" => "0",
"usernameSetted" => "1",
"nicknameSetted" => "0",
"passwordSetted" => "1",
"head_img_url" => "http://s.emao.net/images/common/uc_user_avatar.png",
"avatarSetted" => "0",
"avatar" => "http://s.emao.net/images/common/uc_user_avatar.png",
),
"__serverTime" => "1437385344",
"__serverTimeFormat" => "2015/07/20,17:42:24",
"__openCity" => array
(
"1" => array
(
"cityId" => "1",
"cityName" => "北京",
"pinyin" => "beijing",
"isOpen" => "1",
"insertUser" => "liukang317@emao.com",
"userId" => "90",
"addTime" => "1433153262",
),
"2" => array
(
"cityId" => "2",
"cityName" => "天津",
"pinyin" => "tianjin",
"isOpen" => "1",
"insertUser" => "mall@emao.com",
"userId" => "97",
"addTime" => "1430822126",
),
"169" => array
(
"cityId" => "169",
"cityName" => "武汉",
"pinyin" => "wuhan",
"isOpen" => "1",
"insertUser" => "root",
"userId" => "1",
"addTime" => "1437037629",
),
),
"curCity" => array
(
"cityId" => "1",
"cityName" => "北京",
"pinyin" => "beijing",
),
),
);