<?php
$fis_data=

array
(
"tplData"=>array
(
"autoPoint"=>array
(
"province"=>array
(
"1"=>array
(
"ProvinceId"=>1,
"ProvinceName"=>"北京",
"SingleCity"=>1,
"isUse"=>1,
"sort"=>1,
),

),

"city"=>array
(
"1"=>array
(
"0"=>array
(
"cityId"=>1,
"cityName"=>"北京",
"tag"=>"beijing",
"zipCode"=>100000,
"provinceId"=>1,
"isUse"=>1,
"domain"=>"",
),

),

),

"dealer"=>array
(
"1"=>array
(
"0"=>array
(
"dealerid"=>23263,
"name"=>"一猫公司89测试用-zenglu",
"member"=>"4S店",
"linkName"=>"我是联系人",
"linkPhone"=>13436826128,
"telephone"=>123456789,
"address"=>"中关村",
"provinceId"=>1,
"cityId"=>1,
"longitude"=>"0.000000",
"latitude"=>"0.000000",
"isdel"=>"0",
"istest"=>"0",
"wap_code_img"=>"http://b.bshare.cn/barCode?site=weixin&url=http%3A%2F%2Fdealer.m.emao.com%2F23263%2F",
"province"=>"北京",
"city"=>"北京",
"brand"=>array
(
"166"=>array
(
"brandName"=>"奥迪89测试",
"logo"=>"http://img.emao.net/car/logo/nd/zz/klde.jpg",
"firstWord"=>"A",
"state"=>1,
"brandid"=>166,
"subBrand"=>array
(
"226"=>array
(
"id"=>226,
"subBrandName"=>"一汽奥迪",
"sub_brandid"=>226,
),

"227"=>array
(
"id"=>227,
"subBrandName"=>"上汽奥迪",
"sub_brandid"=>227,
),

),

),

"59"=>array
(
"brandName"=>"雷诺",
"logo"=>"http://img.emao.net/car/logo/nd/bah/gveo.png",
"firstWord"=>"L",
"state"=>1,
"brandid"=>59,
"subBrand"=>array
(
"85"=>array
(
"id"=>85,
"subBrandName"=>"雷诺",
"sub_brandid"=>85,
),

),

),

),

),

),

),

),

"autoDeposit"=>array
(
"0"=>array
(
"id"=>1198,
"gid"=>585,
"giftId"=>41,
"deposit"=>"0",
"sort"=>"0",
"isDef"=>1,
"isFull"=>1,
"isOn"=>1,
"giftInfo"=>array
(
"id"=>41,
"type"=>2,
"cover"=>"/mall/nd/bdg/kaes.png",
"name"=>"3000元节能补贴",
"price"=>3000,
"descr"=>"赠品描述信息",
"addTime"=>1452752766,
"addUser"=>"mall@emao.com",
"state"=>1,
"consumerId"=>23243,
"insertSource"=>1,
"userid"=>"0",
),

),

"1"=>array
(
"id"=>1199,
"gid"=>585,
"giftId"=>39,
"deposit"=>"0",
"sort"=>1,
"isDef"=>"0",
"isFull"=>"0",
"isOn"=>1,
"giftInfo"=>array
(
"id"=>39,
"type"=>1,
"cover"=>"/mall/nd/zz/qmq.jpg",
"name"=>"yw-年底新增赠品",
"price"=>10000,
"descr"=>"测试数据-yw-年底新增赠品",
"addTime"=>1450753006,
"addUser"=>"yanwei256@emao.com",
"state"=>1,
"consumerId"=>23238,
"insertSource"=>1,
"userid"=>"0",
),

),

"2"=>array
(
"id"=>1200,
"gid"=>585,
"giftId"=>37,
"deposit"=>"0",
"sort"=>2,
"isDef"=>"0",
"isFull"=>"0",
"isOn"=>1,
"giftInfo"=>array
(
"id"=>37,
"type"=>3,
"cover"=>"/mall/nd/zz/iilq.jpg",
"name"=>"全车贴膜",
"price"=>5000,
"descr"=>"全车贴膜",
"addTime"=>1447733094,
"addUser"=>"liqiaoxia381@emao.com",
"state"=>1,
"consumerId"=>23245,
"insertSource"=>1,
"userid"=>"0",
),

),

"3"=>array
(
"id"=>1201,
"gid"=>585,
"giftId"=>38,
"deposit"=>"0",
"sort"=>3,
"isDef"=>"0",
"isFull"=>"0",
"isOn"=>1,
"giftInfo"=>array
(
"id"=>38,
"type"=>3,
"cover"=>"/mall/nd/zy/bmkh.png",
"name"=>"阿斯顿发",
"price"=>343,
"descr"=>"阿达说的法",
"addTime"=>1447749697,
"addUser"=>"",
"state"=>1,
"consumerId"=>23236,
"insertSource"=>2,
"userid"=>38687,
),

),

"4"=>array
(
"id"=>1202,
"gid"=>585,
"giftId"=>35,
"deposit"=>"0",
"sort"=>4,
"isDef"=>"0",
"isFull"=>"0",
"isOn"=>1,
"giftInfo"=>array
(
"id"=>35,
"type"=>1,
"cover"=>"/mall/nd/zy/kieg.png",
"name"=>"阿斯顿发",
"price"=>2,
"descr"=>"的",
"addTime"=>1444990570,
"addUser"=>"huangxiaowei539@emao.com",
"state"=>1,
"consumerId"=>23239,
"insertSource"=>1,
"userid"=>"0",
),

),

),

"giftlist"=>array
(
"0"=>array
(
"id"=>41,
"type"=>2,
"cover"=>"/mall/nd/bdg/kaes.png",
"name"=>"3000元节能补贴",
"price"=>3000,
"descr"=>"赠品描述信息",
"addTime"=>1452752766,
"addUser"=>"mall@emao.com",
"state"=>1,
"consumerId"=>23243,
"insertSource"=>1,
"userid"=>"0",
),

"1"=>array
(
"id"=>39,
"type"=>1,
"cover"=>"/mall/nd/zz/qmq.jpg",
"name"=>"yw-年底新增赠品",
"price"=>10000,
"descr"=>"测试数据-yw-年底新增赠品",
"addTime"=>1450753006,
"addUser"=>"yanwei256@emao.com",
"state"=>1,
"consumerId"=>23238,
"insertSource"=>1,
"userid"=>"0",
),

"2"=>array
(
"id"=>37,
"type"=>3,
"cover"=>"/mall/nd/zz/iilq.jpg",
"name"=>"全车贴膜",
"price"=>5000,
"descr"=>"全车贴膜",
"addTime"=>1447733094,
"addUser"=>"liqiaoxia381@emao.com",
"state"=>1,
"consumerId"=>23245,
"insertSource"=>1,
"userid"=>"0",
),

"3"=>array
(
"id"=>38,
"type"=>3,
"cover"=>"/mall/nd/zy/bmkh.png",
"name"=>"阿斯顿发",
"price"=>343,
"descr"=>"阿达说的法",
"addTime"=>1447749697,
"addUser"=>"",
"state"=>1,
"consumerId"=>23236,
"insertSource"=>2,
"userid"=>38687,
),

"4"=>array
(
"id"=>35,
"type"=>1,
"cover"=>"/mall/nd/zy/kieg.png",
"name"=>"阿斯顿发",
"price"=>2,
"descr"=>"的",
"addTime"=>1444990570,
"addUser"=>"huangxiaowei539@emao.com",
"state"=>1,
"consumerId"=>23239,
"insertSource"=>1,
"userid"=>"0",
),

),

"goods"=>array
(
"id"=>585,
"consumerId"=>23274,
"sellType"=>2,
"brandId"=>10,
"subBrandId"=>18,
"serieId"=>193,
"autoId"=>"0",
"smsTitle"=>"",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"root",
"insertTime"=>1459219760,
"updateTime"=>1459220203,
"submitUser"=>"root",
"submitTime"=>1459220173,
"checkUser"=>"root",
"checkTime"=>1459220183,
"backTime"=>"",
"preSellTime"=>1459204200,
"sellTime"=>1459389600,
"underUser"=>"",
"underTxt"=>"",
"under"=>1,
"endSellTime"=>1459409400,
"endSellCount"=>"0",
"isDel"=>"0",
"delUser"=>"",
"delTime"=>"",
"sort"=>"0",
"sortState"=>"0",
"description"=>"",
"isRefund"=>1,
"discountWay"=>"0",
"discount"=>"0",
"contractNo"=>423423421,
"finalTime"=>"",
"sellLead"=>"",
"num"=>"0",
"minPrice"=>"0",
"invoice"=>"0",
"goodsCat"=>12,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>"",
"autoName"=>"",
"fullPayOn"=>1,
"isPurchase"=>"0",
"ticketCount"=>"0",
"goodsName"=>"有下限活动tang-测试商品",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>"",
"insertSource"=>"",
"insertUserId"=>"",
"autoImages"=>"",
"isInstallment"=>2,
"sortPrice_will_delete"=>"",
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>3.00,
"defPrice"=>"0.00",
"isShopshow"=>2,
"__saleState"=>1,
"__lastCategory"=>array
(
"id"=>12,
"pId"=>7,
"depth"=>2,
"name"=>"团购活动(有下限)",
"type"=>1,
"tpl"=>8,
"order"=>4,
),

"__groupGood"=>array
(
"id"=>293,
"gId"=>585,
"entryPrice"=>3.00,
"minGroupnum"=>3,
"maxGroupnum"=>20,
"setDiscount"=>1,
"everyAddnum"=>"0",
"everyDiscount"=>"0.00",
"isShowprice"=>2,
"isGrouprefund"=>1,
"serieNames"=>"<br/>local Test<br/>",
"content"=>"",
"tuanHuodongtime"=>1459305000,
"groupNum"=>"0",
"lastDiscount"=>"",
"giftDesc"=>"赠品说明说明",
"isShowSite"=>1,
"__isTuan"=>"0",
"__series"=>array
(
"18"=>array
(
"subBrandName"=>"广汽本田",
"series"=>array
(
"197"=>array
(
"serieName"=>"凌派",
"photo"=>"http://img.emao.net/car/nd/bae/kuyu.png",
),

"195"=>array
(
"serieName"=>"歌诗图",
"photo"=>"http://img.emao.net/car/nd/yz/jimd.jpg",
),

"194"=>array
(
"serieName"=>"锋范",
"photo"=>"http://img.emao.net/car/nd/yz/jckk.jpg",
),

"193"=>array
(
"serieName"=>"飞度",
"photo"=>"http://img.emao.net/car/nd/yz/lkcz.jpg",
),

),

"brandId"=>10,
"brandlogo"=>"http://img.emao.net/car/logo/nd/bah/bmdc.png",
),

),

"__tuanState"=>1,
"__discount"=>"0",
),

"serviceContent"=>"<br/>local Test<br/>",
"huodongContent"=>"<div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"detail-class\" style=\"height: 40px; margin-top: 10px; position: relative; border-bottom: #dcd7d7 solid 2px;\"><div class=\"class-item\" style=\"position:absolute; z-index:3;  height: 40px; line-height: 40px; color:#414141; font-size: 18px; border-bottom:#df3b58 solid 2px; \">活动时间</div></div></div><div class=\"detail-con-box\"><p><br/></p></div>",
"formatEndSellTime"=>"2016/03/31,15:30:00",
"formatSellTime"=>"2016/03/31,10:00:00",
),

"formHash"=>"5Je4paKlmpy3mp+noKailaGap6Wgppya",
"onlineTalkUri"=>"<br/>local Test<br/>",
"image"=>array
(
"0"=>"http://img.emao.net/mall/nd/bdg/oghu.png",
"1"=>"http://img.emao.net/mall/nd/bdg/cvkl.png",
"2"=>"http://img.emao.net/mall/nd/bdg/jczw.png",
),

"autoParam"=>array
(
),

"pageTitle"=>"有下限活动tang-测试商品_一猫新车商城_买车上一猫",
"pageKeyword"=>"有下限活动tang-测试商品,有下限活动tang-测试商品报价,有下限活动tang-测试商品价格,有下限活动tang-测试商品优惠",
"pageDescription"=>"有下限活动tang-测试商品,",
"adlist"=>array
(
"0"=>array
(
"id"=>22,
"adName"=>"边栏5",
"pic"=>"http://img.emao.net/mall/material/nd/zz/cysb.png",
"linkUrl"=>"http://www.emao.com",
"createTime"=>1451374195,
"updateTime"=>"",
"insertUser"=>"root",
"sort"=>5,
"bgcolor"=>"000000",
"mpic"=>"",
"mlinkUrl"=>"",
"cityId"=>"0",
"cityName"=>"",
"type"=>5,
),

"1"=>array
(
"id"=>21,
"adName"=>"边栏4",
"pic"=>"http://img.emao.net/mall/material/nd/zz/dwye.jpg",
"linkUrl"=>"http://www.emao.com",
"createTime"=>1448522034,
"updateTime"=>"",
"insertUser"=>"root",
"sort"=>4,
"bgcolor"=>"000000",
"mpic"=>"",
"mlinkUrl"=>"",
"cityId"=>"0",
"cityName"=>"",
"type"=>5,
),

"2"=>array
(
"id"=>20,
"adName"=>"边栏3",
"pic"=>"http://img.emao.net/mall/material/nd/zz/calz.png",
"linkUrl"=>"http://www.emao.com",
"createTime"=>1448521993,
"updateTime"=>"",
"insertUser"=>"root",
"sort"=>3,
"bgcolor"=>"000000",
"mpic"=>"",
"mlinkUrl"=>"",
"cityId"=>"0",
"cityName"=>"",
"type"=>5,
),

"3"=>array
(
"id"=>19,
"adName"=>"边栏2",
"pic"=>"http://img.emao.net/mall/material/nd/bdg/gmyz.jpg",
"linkUrl"=>"http://mall.emao.com",
"createTime"=>1451373823,
"updateTime"=>"",
"insertUser"=>"root",
"sort"=>2,
"bgcolor"=>"000000",
"mpic"=>"",
"mlinkUrl"=>"",
"cityId"=>"0",
"cityName"=>"",
"type"=>5,
),

"4"=>array
(
"id"=>18,
"adName"=>"边栏1",
"pic"=>"http://img.emao.net/mall/material/nd/zz/calt.png",
"linkUrl"=>"http://mall.emao.com",
"createTime"=>1448521952,
"updateTime"=>"",
"insertUser"=>"root",
"sort"=>1,
"bgcolor"=>"000000",
"mpic"=>"",
"mlinkUrl"=>"",
"cityId"=>"0",
"cityName"=>"",
"type"=>5,
),

),

"avatar"=>"http://img.emao.net/user/avatar/nd/zz/csob.jpg",
"__loginInfo"=>array
(
"id"=>35215,
"username"=>"eve002",
"nickname"=>"eve002",
"realname"=>"",
"birthday"=>"",
"sex"=>"0",
"selfintro"=>"",
"phone"=>15901501561,
"phoneValid"=>15901501561,
"mail"=>"",
"mailValid"=>"",
"nation_id"=>"0",
"province_id"=>"0",
"city_id"=>"0",
"district_id"=>"0",
"major"=>"",
"mood"=>"",
"tags"=>"",
"head_img_uri"=>"http://img.emao.net/user/avatar/nd/zz/csob.jpg",
"role"=>"0",
"regIP"=>"192.168.20.82",
"login_time"=>"2016-03-29 10:54:55",
"reg_time"=>"2015-02-06 15:43:22",
"update_time"=>"2016-03-29 10:54:55",
"completeStatus"=>7,
"status"=>1,
"source"=>"0",
"client"=>"0",
"auditStatus"=>"0",
"usernameSetted"=>1,
"nicknameSetted"=>1,
"passwordSetted"=>1,
"head_img_url"=>"http://img.emao.nethttp://img.emao.net/user/avatar/nd/zz/csob.jpg",
"avatarSetted"=>1,
"avatar"=>"http://img.emao.net/user/avatar/nd/zz/csob.jpg",
),

"__serverTime"=>1459221654,
"__serverTimeFormat"=>"2016/03/29,11:20:54",
"__http"=>array
(
"mall"=>"http://mall.emao.com",
"mall_m"=>"http://mall.m.emao.com",
"temai"=>"http://mall.emao.com",
"temai_m"=>"http://mall.m.emao.com",
"i"=>"http://i.emao.com",
"i_m"=>"http://i.m.emao.com",
),

),

);