<?php 
$fis_data=
array
(
"tplData"=>array
(
"orderList"=>array
(
"list"=>array
(
"0"=>array
(
"id"=>208,
"orderId"=>315120226396645242883,
"source"=>"0",
"goodId"=>1392,
"userId"=>35630,
"username"=>"lqx000",
"name"=>"-|_ORDER_TEST_|-",
"age"=>"",
"codeType"=>1,
"codeVal"=>513223198209114055,
"phone"=>18633625003,
"colorId"=>2,
"colorName"=>"宝石青",
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"goodsName"=>"整车自采-普通售卖-无订金不全款-不可退款2015-ActiveHybrid 3",
"autoName"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"carProvinceId"=>1,
"carProvinceName"=>"北京",
"carCityId"=>1,
"carCityName"=>"北京",
"pointId"=>23226,
"carDealerId"=>23226,
"carDealerName"=>"北京一猫汽车科技有限公司",
"provinceId"=>"",
"provinceName"=>"",
"autoInfo"=>array
(
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"brandName"=>"宝马",
"subBrandName"=>"宝马(进口)",
"serieName"=>"宝马3系(进口)",
"autoName"=>"ActiveHybrid 3",
"year"=>"ActiveHybrid 3",
),

"partsId"=>"",
"partsGroup"=>"",
"cityId"=>"",
"cityName"=>"",
"bankId"=>59,
"bankName"=>"东张金融",
"firstPayPro"=>1,
"loanRatio"=>"0.000000",
"firstPayMoney"=>"0.00",
"loanMoney"=>"0.00",
"endMoney"=>"0.00",
"countMoney"=>"0.00",
"rateNum"=>1,
"rate"=>"0",
"rateMoney"=>"0.00",
"rateMonth"=>"0.00",
"rateIntMoney"=>"0.00",
"procedureType"=>1,
"procedureVal"=>"0.00",
"freeNum"=>"0",
"emaoPrice"=>"0.00",
"price"=>66.80,
"actualPrice"=>"0.00",
"gift"=>"",
"giftId"=>"0",
"occupation"=>1,
"security"=>1,
"house"=>1,
"extendName"=>"",
"extendPhone"=>"",
"extendEdu"=>"",
"extendIncome"=>"",
"extendLoan"=>"",
"status"=>1,
"remark"=>"",
"addTime"=>1449026396,
"statuslist"=>array
(
),

"securityName"=>"本地社保",
"occupationName"=>"公务员",
"rateNumName"=>"12个月",
"firstPayVal"=>"20%",
"codeTypeName"=>"身份证",
"partsInfo"=>"",
"day_rateMonth"=>"0.00",
"showPro"=>"0.00",
"flow"=>2,
"goodOrderId"=>215120226397586417958,
"takeTime"=>"0",
"deposit"=>"0.00",
"image"=>array
(
"0"=>"http://img.emao.net/car/nd/baj/oweq.jpg",
"1"=>"http://img.emao.net/car/nd/yr/nchq.jpg",
"2"=>"http://img.emao.net/car/nd/yr/hssy.jpg",
"3"=>"http://img.emao.net/car/nd/yr/fqmb.jpg",
"4"=>"http://img.emao.net/car/nd/yr/elyl.jpg",
"5"=>"http://img.emao.net/car/nd/yr/cdrd.jpg",
"6"=>"http://img.emao.net/car/nd/yr/eshu.jpg",
),

"dealer"=>array
(
"name"=>"北京一猫汽车科技有限公司",
"address"=>"北京市海淀区北四环西路52号",
"telephone"=>"010-88888888",
),

"status1"=>array
(
"status"=>1,
"time"=>1449026396,
"statusName"=>"提交成功",
"showline"=>1,
),

"status2"=>array
(
"statusName"=>"一猫审批中",
"showline"=>"0",
),

"status3"=>array
(
"statusName"=>"银行审批中",
"showline"=>"0",
),

"status4"=>array
(
"statusName"=>"完成",
"showline"=>"0",
),

),

"1"=>array
(
"id"=>207,
"orderId"=>315120226350835822608,
"source"=>"0",
"goodId"=>1392,
"userId"=>35630,
"username"=>"lqx000",
"name"=>"-|_ORDER_TEST_|-",
"age"=>"",
"codeType"=>1,
"codeVal"=>513223198209114055,
"phone"=>18810002715,
"colorId"=>2,
"colorName"=>"宝石青",
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"goodsName"=>"整车自采-普通售卖-无订金不全款-不可退款2015-ActiveHybrid 3",
"autoName"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"carProvinceId"=>1,
"carProvinceName"=>"北京",
"carCityId"=>1,
"carCityName"=>"北京",
"pointId"=>23226,
"carDealerId"=>23226,
"carDealerName"=>"北京一猫汽车科技有限公司",
"provinceId"=>"",
"provinceName"=>"",
"autoInfo"=>array
(
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"brandName"=>"宝马",
"subBrandName"=>"宝马(进口)",
"serieName"=>"宝马3系(进口)",
"autoName"=>"ActiveHybrid 3",
"year"=>"ActiveHybrid 3",
),

"partsId"=>"",
"partsGroup"=>"",
"cityId"=>"",
"cityName"=>"",
"bankId"=>59,
"bankName"=>"东张金融",
"firstPayPro"=>1,
"loanRatio"=>"0.000000",
"firstPayMoney"=>"0.00",
"loanMoney"=>"0.00",
"endMoney"=>"0.00",
"countMoney"=>"0.00",
"rateNum"=>1,
"rate"=>"0",
"rateMoney"=>"0.00",
"rateMonth"=>"0.00",
"rateIntMoney"=>"0.00",
"procedureType"=>1,
"procedureVal"=>"0.00",
"freeNum"=>"0",
"emaoPrice"=>"0.00",
"price"=>66.80,
"actualPrice"=>"0.00",
"gift"=>"",
"giftId"=>"0",
"occupation"=>1,
"security"=>1,
"house"=>1,
"extendName"=>"",
"extendPhone"=>"",
"extendEdu"=>"",
"extendIncome"=>"",
"extendLoan"=>"",
"status"=>1,
"remark"=>"",
"addTime"=>1449026350,
"statuslist"=>array
(
),

"securityName"=>"本地社保",
"occupationName"=>"公务员",
"rateNumName"=>"12个月",
"firstPayVal"=>"20%",
"codeTypeName"=>"身份证",
"partsInfo"=>"",
"day_rateMonth"=>"0.00",
"showPro"=>"0.00",
"flow"=>2,
"goodOrderId"=>215120226353152338848,
"takeTime"=>"0",
"deposit"=>"0.00",
"image"=>array
(
"0"=>"http://img.emao.net/car/nd/baj/oweq.jpg",
"1"=>"http://img.emao.net/car/nd/yr/nchq.jpg",
"2"=>"http://img.emao.net/car/nd/yr/hssy.jpg",
"3"=>"http://img.emao.net/car/nd/yr/fqmb.jpg",
"4"=>"http://img.emao.net/car/nd/yr/elyl.jpg",
"5"=>"http://img.emao.net/car/nd/yr/cdrd.jpg",
"6"=>"http://img.emao.net/car/nd/yr/eshu.jpg",
),

"dealer"=>array
(
"name"=>"北京一猫汽车科技有限公司",
"address"=>"北京市海淀区北四环西路52号",
"telephone"=>"010-88888888",
),

"status1"=>array
(
"status"=>1,
"time"=>1449026350,
"statusName"=>"提交成功",
"showline"=>1,
),

"status2"=>array
(
"statusName"=>"一猫审批中",
"showline"=>"0",
),

"status3"=>array
(
"statusName"=>"银行审批中",
"showline"=>"0",
),

"status4"=>array
(
"statusName"=>"完成",
"showline"=>"0",
),

),

"2"=>array
(
"id"=>188,
"orderId"=>315120167464963363207,
"source"=>"0",
"goodId"=>1392,
"userId"=>35630,
"username"=>"lqx000",
"name"=>"-|_ORDER_TEST_|-",
"age"=>"",
"codeType"=>1,
"codeVal"=>513223198209114055,
"phone"=>18810002715,
"colorId"=>1,
"colorName"=>"黑色",
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"goodsName"=>"整车自采-普通售卖-无订金不全款-不可退款2015-ActiveHybrid 3",
"autoName"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"carProvinceId"=>1,
"carProvinceName"=>"北京",
"carCityId"=>1,
"carCityName"=>"北京",
"pointId"=>23226,
"carDealerId"=>23226,
"carDealerName"=>"北京一猫汽车科技有限公司",
"provinceId"=>"",
"provinceName"=>"",
"autoInfo"=>array
(
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"brandName"=>"宝马",
"subBrandName"=>"宝马(进口)",
"serieName"=>"宝马3系(进口)",
"autoName"=>"ActiveHybrid 3",
"year"=>"ActiveHybrid 3",
),

"partsId"=>"",
"partsGroup"=>"",
"cityId"=>"",
"cityName"=>"",
"bankId"=>59,
"bankName"=>"东张金融",
"firstPayPro"=>1,
"loanRatio"=>"0.000000",
"firstPayMoney"=>"0.00",
"loanMoney"=>"0.00",
"endMoney"=>"0.00",
"countMoney"=>"0.00",
"rateNum"=>1,
"rate"=>"0",
"rateMoney"=>"0.00",
"rateMonth"=>"0.00",
"rateIntMoney"=>"0.00",
"procedureType"=>1,
"procedureVal"=>"0.00",
"freeNum"=>"0",
"emaoPrice"=>"0.00",
"price"=>66.80,
"actualPrice"=>"0.00",
"gift"=>"",
"giftId"=>"0",
"occupation"=>1,
"security"=>1,
"house"=>1,
"extendName"=>"",
"extendPhone"=>"",
"extendEdu"=>"",
"extendIncome"=>"",
"extendLoan"=>"",
"status"=>1,
"remark"=>"",
"addTime"=>1448967464,
"statuslist"=>array
(
),

"securityName"=>"本地社保",
"occupationName"=>"公务员",
"rateNumName"=>"12个月",
"firstPayVal"=>"20%",
"codeTypeName"=>"身份证",
"partsInfo"=>"",
"day_rateMonth"=>"0.00",
"showPro"=>"0.00",
"flow"=>2,
"goodOrderId"=>215120167465282145178,
"takeTime"=>"0",
"deposit"=>"0.00",
"image"=>array
(
"0"=>"http://img.emao.net/car/nd/baj/oweq.jpg",
"1"=>"http://img.emao.net/car/nd/yr/nchq.jpg",
"2"=>"http://img.emao.net/car/nd/yr/hssy.jpg",
"3"=>"http://img.emao.net/car/nd/yr/fqmb.jpg",
"4"=>"http://img.emao.net/car/nd/yr/elyl.jpg",
"5"=>"http://img.emao.net/car/nd/yr/cdrd.jpg",
"6"=>"http://img.emao.net/car/nd/yr/eshu.jpg",
),

"dealer"=>array
(
"name"=>"北京一猫汽车科技有限公司",
"address"=>"北京市海淀区北四环西路52号",
"telephone"=>"010-88888888",
),

"status1"=>array
(
"status"=>1,
"time"=>1448967464,
"statusName"=>"提交成功",
"showline"=>1,
),

"status2"=>array
(
"statusName"=>"一猫审批中",
"showline"=>"0",
),

"status3"=>array
(
"statusName"=>"银行审批中",
"showline"=>"0",
),

"status4"=>array
(
"statusName"=>"完成",
"showline"=>"0",
),

),

"3"=>array
(
"id"=>187,
"orderId"=>315120167305624463027,
"source"=>"0",
"goodId"=>1392,
"userId"=>35630,
"username"=>"lqx000",
"name"=>"-|_ORDER_TEST_|-",
"age"=>"",
"codeType"=>1,
"codeVal"=>513223198209114055,
"phone"=>18810002715,
"colorId"=>1,
"colorName"=>"黑色",
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"goodsName"=>"整车自采-普通售卖-无订金不全款-不可退款2015-ActiveHybrid 3",
"autoName"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"carProvinceId"=>1,
"carProvinceName"=>"北京",
"carCityId"=>1,
"carCityName"=>"北京",
"pointId"=>23226,
"carDealerId"=>23226,
"carDealerName"=>"北京一猫汽车科技有限公司",
"provinceId"=>"",
"provinceName"=>"",
"autoInfo"=>array
(
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"brandName"=>"宝马",
"subBrandName"=>"宝马(进口)",
"serieName"=>"宝马3系(进口)",
"autoName"=>"ActiveHybrid 3",
"year"=>"ActiveHybrid 3",
),

"partsId"=>"",
"partsGroup"=>"",
"cityId"=>"",
"cityName"=>"",
"bankId"=>59,
"bankName"=>"东张金融",
"firstPayPro"=>1,
"loanRatio"=>"0.000000",
"firstPayMoney"=>"0.00",
"loanMoney"=>"0.00",
"endMoney"=>"0.00",
"countMoney"=>"0.00",
"rateNum"=>1,
"rate"=>"0",
"rateMoney"=>"0.00",
"rateMonth"=>"0.00",
"rateIntMoney"=>"0.00",
"procedureType"=>1,
"procedureVal"=>"0.00",
"freeNum"=>"0",
"emaoPrice"=>"0.00",
"price"=>66.80,
"actualPrice"=>"0.00",
"gift"=>"",
"giftId"=>"0",
"occupation"=>1,
"security"=>1,
"house"=>1,
"extendName"=>"",
"extendPhone"=>"",
"extendEdu"=>"",
"extendIncome"=>"",
"extendLoan"=>"",
"status"=>1,
"remark"=>"",
"addTime"=>1448967305,
"statuslist"=>array
(
),

"securityName"=>"本地社保",
"occupationName"=>"公务员",
"rateNumName"=>"12个月",
"firstPayVal"=>"20%",
"codeTypeName"=>"身份证",
"partsInfo"=>"",
"day_rateMonth"=>"0.00",
"showPro"=>"0.00",
"flow"=>2,
"goodOrderId"=>215120167306090361233,
"takeTime"=>"0",
"deposit"=>"0.00",
"image"=>array
(
"0"=>"http://img.emao.net/car/nd/baj/oweq.jpg",
"1"=>"http://img.emao.net/car/nd/yr/nchq.jpg",
"2"=>"http://img.emao.net/car/nd/yr/hssy.jpg",
"3"=>"http://img.emao.net/car/nd/yr/fqmb.jpg",
"4"=>"http://img.emao.net/car/nd/yr/elyl.jpg",
"5"=>"http://img.emao.net/car/nd/yr/cdrd.jpg",
"6"=>"http://img.emao.net/car/nd/yr/eshu.jpg",
),

"dealer"=>array
(
"name"=>"北京一猫汽车科技有限公司",
"address"=>"北京市海淀区北四环西路52号",
"telephone"=>"010-88888888",
),

"status1"=>array
(
"status"=>1,
"time"=>1448967305,
"statusName"=>"提交成功",
"showline"=>0,
),

"status2"=>array
(
"statusName"=>"一猫审批中",
"showline"=>"0",
),

"status3"=>array
(
"statusName"=>"银行审批中",
"showline"=>"0",
),

"status4"=>array
(
"statusName"=>"完成",
"showline"=>"1",
),

),

"4"=>array
(
"id"=>186,
"orderId"=>315120167239256015446,
"source"=>"0",
"goodId"=>1392,
"userId"=>35630,
"username"=>"lqx000",
"name"=>"-|_ORDER_TEST_|-",
"age"=>"",
"codeType"=>1,
"codeVal"=>513223198209114055,
"phone"=>18810002715,
"colorId"=>1,
"colorName"=>"黑色",
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"goodsName"=>"整车自采-普通售卖-无订金不全款-不可退款2015-ActiveHybrid 3",
"autoName"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"carProvinceId"=>1,
"carProvinceName"=>"北京",
"carCityId"=>1,
"carCityName"=>"北京",
"pointId"=>23226,
"carDealerId"=>23226,
"carDealerName"=>"北京一猫汽车科技有限公司",
"provinceId"=>"",
"provinceName"=>"",
"autoInfo"=>array
(
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"brandName"=>"宝马",
"subBrandName"=>"宝马(进口)",
"serieName"=>"宝马3系(进口)",
"autoName"=>"ActiveHybrid 3",
"year"=>"ActiveHybrid 3",
),

"partsId"=>"",
"partsGroup"=>"",
"cityId"=>"",
"cityName"=>"",
"bankId"=>59,
"bankName"=>"东张金融",
"firstPayPro"=>1,
"loanRatio"=>"0.000000",
"firstPayMoney"=>"0.00",
"loanMoney"=>"0.00",
"endMoney"=>"0.00",
"countMoney"=>"0.00",
"rateNum"=>1,
"rate"=>"0",
"rateMoney"=>"0.00",
"rateMonth"=>"0.00",
"rateIntMoney"=>"0.00",
"procedureType"=>1,
"procedureVal"=>"0.00",
"freeNum"=>"0",
"emaoPrice"=>"0.00",
"price"=>66.80,
"actualPrice"=>"0.00",
"gift"=>"",
"giftId"=>"0",
"occupation"=>1,
"security"=>1,
"house"=>1,
"extendName"=>"",
"extendPhone"=>"",
"extendEdu"=>"",
"extendIncome"=>"",
"extendLoan"=>"",
"status"=>1,
"remark"=>"",
"addTime"=>1448967239,
"statuslist"=>array
(
),

"securityName"=>"本地社保",
"occupationName"=>"公务员",
"rateNumName"=>"12个月",
"firstPayVal"=>"20%",
"codeTypeName"=>"身份证",
"partsInfo"=>"",
"day_rateMonth"=>"0.00",
"showPro"=>"0.00",
"flow"=>2,
"goodOrderId"=>215120167239478239173,
"takeTime"=>"0",
"deposit"=>"0.00",
"image"=>array
(
"0"=>"http://img.emao.net/car/nd/baj/oweq.jpg",
"1"=>"http://img.emao.net/car/nd/yr/nchq.jpg",
"2"=>"http://img.emao.net/car/nd/yr/hssy.jpg",
"3"=>"http://img.emao.net/car/nd/yr/fqmb.jpg",
"4"=>"http://img.emao.net/car/nd/yr/elyl.jpg",
"5"=>"http://img.emao.net/car/nd/yr/cdrd.jpg",
"6"=>"http://img.emao.net/car/nd/yr/eshu.jpg",
),

"dealer"=>array
(
"name"=>"北京一猫汽车科技有限公司",
"address"=>"北京市海淀区北四环西路52号",
"telephone"=>"010-88888888",
),

"status1"=>array
(
"status"=>1,
"time"=>1448967239,
"statusName"=>"提交成功",
"showline"=>0,
),

"status2"=>array
(
"statusName"=>"一猫审批中",
"showline"=>"0",
),

"status3"=>array
(
"statusName"=>"银行审批中",
"showline"=>"1",
),

"status4"=>array
(
"statusName"=>"完成",
"showline"=>"0",
),

),

),

"page"=>array
(
"count"=>60,
"page"=>1,
"pagesize"=>5,
),

),

"onlineTalkUri"=>"<br/>local Test<br/>",
"pageTitle"=>"我的分期订单_一猫新车商城",
"pageKeyword"=>"汽车商城,一猫新车商城",
"pageDescription"=>"我在一猫新车商城中的分期订单",
"__loginInfo"=>array
(
"id"=>35630,
"username"=>"lqx000",
"nickname"=>"lqx000",
"realname"=>"",
"birthday"=>"",
"sex"=>-1,
"selfintro"=>"",
"phone"=>"",
"phoneValid"=>13718863804,
"mail"=>"",
"mailValid"=>"",
"nation_id"=>"0",
"province_id"=>"0",
"city_id"=>"0",
"district_id"=>"0",
"major"=>"",
"mood"=>"ccc",
"tags"=>"",
"head_img_uri"=>"http://s.emao.net/images/common/uc_user_avatar.png",
"role"=>"0",
"regIP"=>"192.168.20.155",
"login_time"=>"2015-12-17 17:15:45",
"reg_time"=>"2015-06-02 10:42:48",
"update_time"=>"2015-12-17 17:20:02",
"completeStatus"=>5,
"status"=>1,
"source"=>"0",
"client"=>1,
"auditStatus"=>"0",
"usernameSetted"=>1,
"nicknameSetted"=>"0",
"passwordSetted"=>1,
"head_img_url"=>"http://s.emao.net/images/common/uc_user_avatar.png",
"avatarSetted"=>"0",
"avatar"=>"http://s.emao.net/images/common/uc_user_avatar.png",
),

"__serverTime"=>1450344328,
"__serverTimeFormat"=>"2015/12/17,17:25:28",
"__http"=>array
(
"mall"=>"http://mall.emao.com",
"mall_m"=>"http://mall.m.emao.com",
"temai"=>"http://mall.emao.com",
"temai_m"=>"http://mall.m.emao.com",
"i"=>"http://i.emao.com",
"i_m"=>"http://i.m.emao.com",
),

),

);