<?php 
$fis_data=

array
(
"tplData"=>array
(
"autoId"=>"undefined",
"serieNames"=>array
(
"0"=>array
(
"brandId"=>2,
"subBrandId"=>2,
"serieId"=>11,
"brandName"=>"奥迪",
"subBrandName"=>"一汽奥迪",
"serieName"=>"奥迪Q3",
),

"1"=>array
(
"brandId"=>2,
"subBrandId"=>2,
"serieId"=>10,
"brandName"=>"奥迪",
"subBrandName"=>"一汽奥迪",
"serieName"=>"奥迪Q5",
),

"2"=>array
(
"brandId"=>2,
"subBrandId"=>2,
"serieId"=>9,
"brandName"=>"奥迪",
"subBrandName"=>"一汽奥迪",
"serieName"=>"奥迪A6L",
),

),

"subBrandNameArr"=>array
(
"0"=>"一汽奥迪",
"1"=>"一汽大众",
"2"=>"一汽奥迪",
"3"=>"一汽大众",
"4"=>"一汽奥迪",
"5"=>"一汽大众",
"6"=>"一汽奥迪",
"7"=>"一汽大众",
"8"=>"一汽奥迪",
"9"=>"一汽大众",
),

"serieName"=>"-",
"autoName"=>"-",
"autoPic"=>"http://img.emao.net/car/test.jpg/31",
"city"=>"北京",
"dealerName"=>"黄小伟的测试公司a05黄小伟的测试公司a05黄小伟的测试公司",
"cityId"=>1,
"dealerid"=>23268,
"goodsId"=>181,
"pointId"=>23268,
"formhash"=>"5Je4paKpnJe3mp+lpKSclaOepKqgppya",
"tpl"=>8,
"emaoPrice"=>"0",
"orderPrice"=>"0",
"offlinePrice"=>"0",
"discount"=>"",
"gType"=>3,
"consumerId"=>23268,
"ticketCount"=>"0",
"giftInfo"=>"",
"pageTitle"=>"确认订单_一猫新车商城",
"pageKeyword"=>"确认订单,一猫新车商城,一猫商城,一猫汽车,网上汽车商城,在线买车,特价车商城,汽车商城,买车网,购车网",
"pageDescription"=>"一猫新车商城是新型的网商购车体验平台，为用户提供在线购买汽车服务并可享受一猫网全程专业的选车、选商家等指导服务，还可以获得现金优惠券加油卡等礼包。买车上一猫。",
"__loginInfo"=>array
(
"id"=>35630,
"username"=>"lqx000",
"nickname"=>"lqx000",
"realname"=>"",
"birthday"=>"",
"sex"=>"0",
"selfintro"=>"",
"phone"=>"",
"phoneValid"=>13718863804,
"mail"=>"",
"mailValid"=>"",
"nation_id"=>"0",
"province_id"=>"0",
"city_id"=>"0",
"district_id"=>"0",
"major"=>"",
"mood"=>"ccc",
"tags"=>"",
"head_img_uri"=>"http://img.emao.net/user/avatar/nd/zz/jaei.jpg",
"role"=>"0",
"regIP"=>"192.168.20.155",
"login_time"=>"2016-01-21 14:20:06",
"reg_time"=>"2015-06-02 10:42:48",
"update_time"=>"2016-01-21 14:20:06",
"completeStatus"=>7,
"status"=>1,
"source"=>"0",
"client"=>1,
"auditStatus"=>"0",
"usernameSetted"=>1,
"nicknameSetted"=>1,
"passwordSetted"=>1,
"head_img_url"=>"http://img.emao.nethttp://img.emao.net/user/avatar/nd/zz/jaei.jpg",
"avatarSetted"=>1,
"avatar"=>"http://img.emao.net/user/avatar/nd/zz/jaei.jpg",
),

"__serverTime"=>1453368909,
"__serverTimeFormat"=>"2016/01/21,17:35:09",
"__http"=>array
(
"mall"=>"http://mall.emao.com",
"mall_m"=>"http://mall.m.emao.com",
"temai"=>"http://mall.emao.com",
"temai_m"=>"http://mall.m.emao.com",
"i"=>"http://i.emao.com",
"i_m"=>"http://i.m.emao.com",
),

),

);