<?php 
 $fis_data=
Array
(
"tplData"=> array
(
"colorId"=> "1",
"color"=> "幻影黑",
"depositId"=> "1453",
"serieName"=> "奥迪A4L",
"autoName"=> "2015-35 TFSI 自动豪华型",
"ticket"=> array
(
"0"=> array
(
"id"=> "57",
"sn"=> "F8TNDSLHVKR3QBYW",
"batchId"=> "57",
"userId"=> "35630",
"orderId"=> "",
"cancel"=> "2",
"isRelease"=> "1",
"name"=> "zgltest",
"type"=> "1",
"note"=> "fdasfdsafsd",
"startTime"=> "1444521600",
"endTime"=> "1446910200",
"price"=> "500",
"number"=> "50",
"useScene"=> "2",
"useRange"=> "2",
"state"=> "1",
),
),
"autoPic"=> "http://img.emao.net/car/test.jpg",
"city"=> "北京",
"dealerName"=> "G商城测试商户A",
"goodsId"=> "1670",
"pointId"=> "23202",
"formhash"=> "5Je4paKpnJe3mp+joaidlaKWpKeiqJ6d",
"tpl"=> "1",
"orderPrice"=> "0.01",
"emaoPrice"=> "0.01",
"discount"=> "0",
"gType"=> "2",
"consumerId"=> "23202",
"ticketCount"=> "3",
"giftInfo"=> array
(
"id"=> "63",
"type"=> "3",
"cover"=> "/mall/nd/bai/czlz.jpg",
"name"=> "赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品赠品",
"price"=> "100.00",
"descr"=> "",
"addTime"=> "1441620287",
"addUser"=> "",
"state"=> "1",
"consumerId"=> "23202",
"insertSource"=> "2",
"userid"=> "35506",
),
"pageTitle"=> "确认订单_特卖商城_一猫汽车商城",
"pageKeyword"=> "确认订单,特卖商城,一猫汽车商城,新车商城",
"pageDescription"=> "一猫汽车商城提供用户在线购买汽车并可享受一猫网全程专业的指导、选车、选商家，车主可获得一猫购车现金券等多项专属优惠。",
"__loginInfo"=> array
(
"id"=> "35630",
"username"=> "lqx000",
"nickname"=> "lqx000",
"realname"=> "",
"birthday"=> "",
"sex"=> "-1",
"selfintro"=> "",
"phone"=> "",
"phoneValid"=> "13718863804",
"mail"=> "",
"mailValid"=> "",
"nation_id"=> "0",
"province_id"=> "0",
"city_id"=> "0",
"district_id"=> "0",
"major"=> "",
"mood"=> "ccc",
"tags"=> "",
"head_img_uri"=> "http://s.emao.net/images/common/uc_user_avatar.png",
"role"=> "0",
"regIP"=> "192.168.20.155",
"login_time"=> "2015-10-19 11:33:54",
"reg_time"=> "2015-06-02 10:42:48",
"update_time"=> "2015-10-19 11:33:54",
"completeStatus"=> "5",
"status"=> "1",
"source"=> "0",
"client"=> "1",
"auditStatus"=> "0",
"usernameSetted"=> "1",
"nicknameSetted"=> "0",
"passwordSetted"=> "1",
"head_img_url"=> "http://s.emao.net/images/common/uc_user_avatar.png",
"avatarSetted"=> "0",
"avatar"=> "http://s.emao.net/images/common/uc_user_avatar.png",
),
"__serverTime"=> "1445235860",
"__serverTimeFormat"=> "2015/10/19,14:24:20",
"__http"=> array
(
"mall"=> "http://mall.emao.com",
"mall_m"=> "http://mall.m.emao.com",
"temai"=> "http://mall.emao.com",
"temai_m"=> "http://mall.m.emao.com",
"i"=> "http://i.emao.com",
"i_m"=> "http://i.m.emao.com",
),
),
);