<?php 
 $fis_data=Array
(
"tplData" => array
(
"curCity" => array
(
"cityId" => "1",
"cityName" => "北京",
"pinyin" => "beijing",
"isOpen" => "1",
"insertUser" => "liukang317@emao.com",
"userId" => "90",
"addTime" => "1433153262",
),
"ad" => array
(
"7" => array
(
"id" => "7",
"adName" => "特价车商城的首页轮播展示与查看",
"pic" => "http://img.emao.net/mall/material/nd/bal/jcys.jpg",
"linkUrl" => "http://www.emao.com",
"createTime" => "1437377120",
"updateTime" => "",
"insertUser" => "root",
"sort" => "5",
"bgcolor" => "000000",
"mpic" => "http://img.emao.net/mall/material/nd/bal/nobz.jpg",
"mlinkUrl" => "http://m.emao.com",
),
"2" => array
(
"id" => "2",
"adName" => "rrrrrrrrrrr1",
"pic" => "http://img.emao.net/mall/material/nd/bak/ndan.jpg",
"linkUrl" => "",
"createTime" => "1433212006",
"updateTime" => "",
"insertUser" => "liukang317@emao.com",
"sort" => "4",
"bgcolor" => "131925",
"mpic" => "http://img.emao.net/mall/material/nd/bak/hklr.jpg",
"mlinkUrl" => "http://www.baidu.com",
),
),
"recBrand" => array
(
"1" => array
(
"id" => "1",
"brandName" => "阿斯顿·马丁",
"logo" => "http://img.emao.net/car/logo/nd/bah/oxp.png",
"website" => "http://www.astonmartin-china.com",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => " 阿斯顿·马丁（AstonMartin）公司设在英国盖顿，生产敞篷旅行车、赛车和限量生产的跑车。建于1913年，创始人是莱昂内尔·马丁和罗伯特·班。1987年被美国福特公司收购。2007年，Prodrive老板大卫·理查兹以9.25亿美元的价格从福特手中购得阿斯顿·马丁。",
"companyName" => "阿斯顿·马丁",
"foreignName" => "Aston Martin",
"address" => "英国盖顿",
"foundDate" => "0000-00-00",
"meaning" => "阿斯顿·马丁汽车标志为一只展翅飞翔的大鹏，喻示该公司像大鹏鸟一样，具有从天而降的冲刺速度和远大的志向。",
"scope" => "高端赛车、跑车、敞篷旅行车",
"staff" => "0",
"founder" => "莱昂内尔·马丁、罗伯特·班福德",
"slogan" => "",
"story" => "",
"recommend" => "1",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-07-21 11:05:04",
"message" => "0",
"source" => "1",
"carscmsId" => "1",
"carscmsCountry" => "英国",
),
"2" => array
(
"id" => "2",
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"website" => "http://www.audi.cn/cn/brand/zh.html",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "奥迪（Audi）是一个国际著名豪华汽车品牌，作为高技术水平、质量标准、创新能力、以及经典车型款式的代表，奥迪是世界最成功的汽车品牌之一。公司总部设在德国的英戈尔施塔特。",
"companyName" => "奥迪汽车公司",
"foreignName" => "Audi",
"address" => "德国 英戈尔施塔特",
"foundDate" => "1910-04-25",
"meaning" => "奥迪轿车的标志为四个圆环，代表着合并前的四家公司。",
"scope" => "高端汽车的生产",
"staff" => "0",
"founder" => "奥古斯特·霍希",
"slogan" => "突破科技，启迪未来。",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:13",
"message" => "0",
"source" => "1",
"carscmsId" => "2",
"carscmsCountry" => "德国",
),
"4" => array
(
"id" => "4",
"brandName" => "宝骏",
"logo" => "http://img.emao.net/car/logo/nd/bah/oikc.png",
"website" => "http://www.autobaojun.com/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "宝骏是上汽通用五菱2010年创建的自主汽车品牌。上汽通用五菱正式发布的新乘用车品牌“宝骏汽车”，标志这个中国微车领头羊开始正式进军方兴未艾的轿车市场。宝骏品牌源由：“骏”的本义是良驹，宝骏即人们最心爱的良驹。",
"companyName" => "上海通用",
"foreignName" => "shanghaitongyong",
"address" => "",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "",
"staff" => "0",
"founder" => "",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-10 17:18:55",
"message" => "0",
"source" => "1",
"carscmsId" => "4",
"carscmsCountry" => "自主",
),
"5" => array
(
"id" => "5",
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"website" => "http://www.bmw.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "宝马汽车为德系三大豪华品牌之一，宝马的车系有1、2、3、4、5、6、7、i、X、Z等几个系列，还有在各系基础上进行改进的M系（宝马官方的高性能改装部门）。宝马公司创建于1916年，总部设在德国慕尼黑。",
"companyName" => "巴伐利亚机械制造厂股份公司",
"foreignName" => "BayerischeMotorenWerke AG",
"address" => "德国慕尼黑",
"foundDate" => "1916-03-07",
"meaning" => "BMW的蓝白标志象征着蓝天,白云和旋转的螺旋桨。",
"scope" => "高端汽车及摩托车的生产",
"staff" => "0",
"founder" => "吉斯坦·奥托(Gustan Otto)",
"slogan" => "Sheer Driving Pleasure（纯粹驾驶乐趣）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:24",
"message" => "0",
"source" => "1",
"carscmsId" => "5",
"carscmsCountry" => "德国",
),
"6" => array
(
"id" => "6",
"brandName" => "保时捷",
"logo" => "http://img.emao.net/car/logo/nd/bah/kvmy.png",
"website" => "http://www.porsche.com/china/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "保时捷，是德国汽车品牌，1930年由费迪南德·波尔舍教授建于斯图加特。费迪南德·波尔舍是一位享誉世界车坛的著名设计师。保时捷以生产高级跑车而著名于世界车坛。在1932年的巴黎国际展览会上，保时捷已经名扬四海。保时捷汽车具有鲜明的特色，甲壳虫式的车形，后置式发动机和优异的性能，令它很快成为知名的汽车。",
"companyName" => "德国保时捷公司",
"foreignName" => "Porsche",
"address" => "德国斯图加特",
"foundDate" => "1931-04-25",
"meaning" => "通过一幅优美的田园风景画，展现了保时捷公司辉煌的过去，预示了美好的未来及保时捷跑车的出类拔萃。",
"scope" => "高端汽车的开发、生产、营销",
"staff" => "0",
"founder" => "费迪南德·保时捷",
"slogan" => "There Is No Substitute（无可替代）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:32",
"message" => "0",
"source" => "1",
"carscmsId" => "6",
"carscmsCountry" => "德国",
),
"10" => array
(
"id" => "10",
"brandName" => "本田",
"logo" => "http://img.emao.net/car/logo/nd/bah/bmdc.png",
"website" => "http://www.honda.com.cn/",
"firstWord" => "B",
"ssi" => "10",
"csi" => "2",
"classId" => "2",
"intro" => "本田株式会社（本田技研工业株式会社）是世界上最大的摩托车生产厂家，汽车产量和规模也名列世界十大汽车厂家之列。1948年创立，创始人是传奇式人物本田宗一郎。公司总部在东京，雇员总数达18万人左右。现在，本田公司已是一个跨国汽车、摩托车生产销售集团。它的产品除汽车、摩托车外，还有发电机、农机等动力机械产品。",
"companyName" => "本田株式会社",
"foreignName" => "HONDA",
"address" => "日本东京都港区南青山2-1-1",
"foundDate" => "1948-09-09",
"meaning" => "飞跃的本田的技术和本田公司前途无量",
"scope" => "汽车、摩托车",
"staff" => "0",
"founder" => "本田宗一郎",
"slogan" => "让孩子的天空更蔚蓝",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 18:31:31",
"message" => "0",
"source" => "1",
"carscmsId" => "10",
"carscmsCountry" => "日本",
),
"13" => array
(
"id" => "13",
"brandName" => "别克",
"logo" => "http://img.emao.net/car/logo/nd/bah/gvmt.png",
"website" => "http://www.buick.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "15",
"classId" => "2",
"intro" => "别克（Buick），是由美国通用汽车公司在美国、加拿大和中国创立的一个品牌。它在北美、中国、独联体国家以及中东都有销售。",
"companyName" => "别克汽车公司",
"foreignName" => "BUICK",
"address" => "美国",
"foundDate" => "1904-05-14",
"meaning" => "象征着一种积极进取，不断登攀的精神。",
"scope" => "中高端汽车生产",
"staff" => "0",
"founder" => "大卫 ·邓巴· 别克",
"slogan" => "用心超越，品味无限。",
"story" => "",
"recommend" => "0",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-07-23 14:36:16",
"message" => "0",
"source" => "1",
"carscmsId" => "13",
"carscmsCountry" => "美国",
),
"9" => array
(
"id" => "9",
"brandName" => "奔腾",
"logo" => "http://img.emao.net/car/logo/nd/bah/iryx.png",
"website" => "http://www.faw-benteng.com/",
"firstWord" => "B",
"ssi" => "1",
"csi" => "1",
"classId" => "1",
"intro" => "奔腾是一汽集团中最“年轻”的品牌之一。作为自主轿车品牌，奔腾依旧采用了高装备、低价格的销售策略，与马自达6共用主要零部件的生产方式也让奔腾品牌轿车主要部件的质量达到了与合资产品相同的水平，从这一点上讲，奔腾产品的核心实力要大于同期的其它自主品牌轿车。",
"companyName" => "一汽轿车",
"foreignName" => "besturn",
"address" => "长春市",
"foundDate" => "2006-08-18",
"meaning" => "品质、性能、科技",
"scope" => "开发、制造、销售乘用车、发动机、变速箱及其配件。",
"staff" => "0",
"founder" => "郭力",
"slogan" => "进取不止",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-11 10:41:19",
"message" => "0",
"source" => "1",
"carscmsId" => "9",
"carscmsCountry" => "中国",
),
),
"openBrand" => array
(
"A" => array
(
"0" => array
(
"id" => "1",
"brandName" => "阿斯顿·马丁",
"logo" => "http://img.emao.net/car/logo/nd/bah/oxp.png",
"website" => "http://www.astonmartin-china.com",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => " 阿斯顿·马丁（AstonMartin）公司设在英国盖顿，生产敞篷旅行车、赛车和限量生产的跑车。建于1913年，创始人是莱昂内尔·马丁和罗伯特·班。1987年被美国福特公司收购。2007年，Prodrive老板大卫·理查兹以9.25亿美元的价格从福特手中购得阿斯顿·马丁。",
"companyName" => "阿斯顿·马丁",
"foreignName" => "Aston Martin",
"address" => "英国盖顿",
"foundDate" => "0000-00-00",
"meaning" => "阿斯顿·马丁汽车标志为一只展翅飞翔的大鹏，喻示该公司像大鹏鸟一样，具有从天而降的冲刺速度和远大的志向。",
"scope" => "高端赛车、跑车、敞篷旅行车",
"staff" => "0",
"founder" => "莱昂内尔·马丁、罗伯特·班福德",
"slogan" => "",
"story" => "",
"recommend" => "1",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-07-21 11:05:04",
"message" => "0",
"source" => "1",
"carscmsId" => "1",
"carscmsCountry" => "英国",
),
"1" => array
(
"id" => "2",
"brandName" => "奥迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ivq.png",
"website" => "http://www.audi.cn/cn/brand/zh.html",
"firstWord" => "A",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "奥迪（Audi）是一个国际著名豪华汽车品牌，作为高技术水平、质量标准、创新能力、以及经典车型款式的代表，奥迪是世界最成功的汽车品牌之一。公司总部设在德国的英戈尔施塔特。",
"companyName" => "奥迪汽车公司",
"foreignName" => "Audi",
"address" => "德国 英戈尔施塔特",
"foundDate" => "1910-04-25",
"meaning" => "奥迪轿车的标志为四个圆环，代表着合并前的四家公司。",
"scope" => "高端汽车的生产",
"staff" => "0",
"founder" => "奥古斯特·霍希",
"slogan" => "突破科技，启迪未来。",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:13",
"message" => "0",
"source" => "1",
"carscmsId" => "2",
"carscmsCountry" => "德国",
),
),
"B" => array
(
"0" => array
(
"id" => "4",
"brandName" => "宝骏",
"logo" => "http://img.emao.net/car/logo/nd/bah/oikc.png",
"website" => "http://www.autobaojun.com/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "宝骏是上汽通用五菱2010年创建的自主汽车品牌。上汽通用五菱正式发布的新乘用车品牌“宝骏汽车”，标志这个中国微车领头羊开始正式进军方兴未艾的轿车市场。宝骏品牌源由：“骏”的本义是良驹，宝骏即人们最心爱的良驹。",
"companyName" => "上海通用",
"foreignName" => "shanghaitongyong",
"address" => "",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "",
"staff" => "0",
"founder" => "",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-10 17:18:55",
"message" => "0",
"source" => "1",
"carscmsId" => "4",
"carscmsCountry" => "自主",
),
"1" => array
(
"id" => "3",
"brandName" => "BRABUS巴博斯",
"logo" => "http://img.emao.net/car/logo/nd/bah/lboj.png",
"website" => "http://www.brabuschina.com/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "BRABUS公司由Bodo Buschmann 先生创建于1977年，现已跻身为全球最大的汽车改装厂商之一。",
"companyName" => "博速公司",
"foreignName" => "BRABUS",
"address" => "鲁尔区",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "汽车改装",
"staff" => "0",
"founder" => "Bodo Buschmann",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-04-15 11:21:48",
"message" => "0",
"source" => "1",
"carscmsId" => "3",
"carscmsCountry" => "德国",
),
"2" => array
(
"id" => "5",
"brandName" => "宝马",
"logo" => "http://img.emao.net/car/logo/nd/bah/dprj.png",
"website" => "http://www.bmw.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "宝马汽车为德系三大豪华品牌之一，宝马的车系有1、2、3、4、5、6、7、i、X、Z等几个系列，还有在各系基础上进行改进的M系（宝马官方的高性能改装部门）。宝马公司创建于1916年，总部设在德国慕尼黑。",
"companyName" => "巴伐利亚机械制造厂股份公司",
"foreignName" => "BayerischeMotorenWerke AG",
"address" => "德国慕尼黑",
"foundDate" => "1916-03-07",
"meaning" => "BMW的蓝白标志象征着蓝天,白云和旋转的螺旋桨。",
"scope" => "高端汽车及摩托车的生产",
"staff" => "0",
"founder" => "吉斯坦·奥托(Gustan Otto)",
"slogan" => "Sheer Driving Pleasure（纯粹驾驶乐趣）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:24",
"message" => "0",
"source" => "1",
"carscmsId" => "5",
"carscmsCountry" => "德国",
),
"3" => array
(
"id" => "6",
"brandName" => "保时捷",
"logo" => "http://img.emao.net/car/logo/nd/bah/kvmy.png",
"website" => "http://www.porsche.com/china/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "3",
"intro" => "保时捷，是德国汽车品牌，1930年由费迪南德·波尔舍教授建于斯图加特。费迪南德·波尔舍是一位享誉世界车坛的著名设计师。保时捷以生产高级跑车而著名于世界车坛。在1932年的巴黎国际展览会上，保时捷已经名扬四海。保时捷汽车具有鲜明的特色，甲壳虫式的车形，后置式发动机和优异的性能，令它很快成为知名的汽车。",
"companyName" => "德国保时捷公司",
"foreignName" => "Porsche",
"address" => "德国斯图加特",
"foundDate" => "1931-04-25",
"meaning" => "通过一幅优美的田园风景画，展现了保时捷公司辉煌的过去，预示了美好的未来及保时捷跑车的出类拔萃。",
"scope" => "高端汽车的开发、生产、营销",
"staff" => "0",
"founder" => "费迪南德·保时捷",
"slogan" => "There Is No Substitute（无可替代）",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-12 11:08:32",
"message" => "0",
"source" => "1",
"carscmsId" => "6",
"carscmsCountry" => "德国",
),
"4" => array
(
"id" => "10",
"brandName" => "本田",
"logo" => "http://img.emao.net/car/logo/nd/bah/bmdc.png",
"website" => "http://www.honda.com.cn/",
"firstWord" => "B",
"ssi" => "10",
"csi" => "2",
"classId" => "2",
"intro" => "本田株式会社（本田技研工业株式会社）是世界上最大的摩托车生产厂家，汽车产量和规模也名列世界十大汽车厂家之列。1948年创立，创始人是传奇式人物本田宗一郎。公司总部在东京，雇员总数达18万人左右。现在，本田公司已是一个跨国汽车、摩托车生产销售集团。它的产品除汽车、摩托车外，还有发电机、农机等动力机械产品。",
"companyName" => "本田株式会社",
"foreignName" => "HONDA",
"address" => "日本东京都港区南青山2-1-1",
"foundDate" => "1948-09-09",
"meaning" => "飞跃的本田的技术和本田公司前途无量",
"scope" => "汽车、摩托车",
"staff" => "0",
"founder" => "本田宗一郎",
"slogan" => "让孩子的天空更蔚蓝",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 18:31:31",
"message" => "0",
"source" => "1",
"carscmsId" => "10",
"carscmsCountry" => "日本",
),
"5" => array
(
"id" => "13",
"brandName" => "别克",
"logo" => "http://img.emao.net/car/logo/nd/bah/gvmt.png",
"website" => "http://www.buick.com.cn/",
"firstWord" => "B",
"ssi" => "0",
"csi" => "15",
"classId" => "2",
"intro" => "别克（Buick），是由美国通用汽车公司在美国、加拿大和中国创立的一个品牌。它在北美、中国、独联体国家以及中东都有销售。",
"companyName" => "别克汽车公司",
"foreignName" => "BUICK",
"address" => "美国",
"foundDate" => "1904-05-14",
"meaning" => "象征着一种积极进取，不断登攀的精神。",
"scope" => "中高端汽车生产",
"staff" => "0",
"founder" => "大卫 ·邓巴· 别克",
"slogan" => "用心超越，品味无限。",
"story" => "",
"recommend" => "0",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-07-23 14:36:16",
"message" => "0",
"source" => "1",
"carscmsId" => "13",
"carscmsCountry" => "美国",
),
"6" => array
(
"id" => "11",
"brandName" => "比亚迪",
"logo" => "http://img.emao.net/car/logo/nd/bah/ilxh.png",
"website" => "http://www.bydauto.com.cn",
"firstWord" => "B",
"ssi" => "0",
"csi" => "0",
"classId" => "1",
"intro" => "比亚迪股份有限公司创立于1995年，2002年7月31日在香港主板发行上市，公司总部位于中华人民共和国广东省深圳市，是一家拥有IT，汽车和新能源三大产业群的高新技术民营企业。比亚迪在广东、北京、陕西、上海等地共建有九大生产基地，总面积将近700万平方米，并在美国、欧洲、日本、韩国、印度等国和中国台湾、香港地区设有分公司或办事处，现员工总数超过15万人。",
"companyName" => "比亚迪股份有限公司",
"foreignName" => "BYD",
"address" => "中国深圳坪山区比亚迪路3009号",
"foundDate" => "1995-10-28",
"meaning" => "build your dreams（成就梦想）",
"scope" => "IT、汽车、新能源",
"staff" => "0",
"founder" => "王传福",
"slogan" => "平等、务实、激情、创新",
"story" => "",
"recommend" => "1",
"hot" => "1",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-11 10:37:12",
"message" => "0",
"source" => "1",
"carscmsId" => "11",
"carscmsCountry" => "自主",
),
"7" => array
(
"id" => "9",
"brandName" => "奔腾",
"logo" => "http://img.emao.net/car/logo/nd/bah/iryx.png",
"website" => "http://www.faw-benteng.com/",
"firstWord" => "B",
"ssi" => "1",
"csi" => "1",
"classId" => "1",
"intro" => "奔腾是一汽集团中最“年轻”的品牌之一。作为自主轿车品牌，奔腾依旧采用了高装备、低价格的销售策略，与马自达6共用主要零部件的生产方式也让奔腾品牌轿车主要部件的质量达到了与合资产品相同的水平，从这一点上讲，奔腾产品的核心实力要大于同期的其它自主品牌轿车。",
"companyName" => "一汽轿车",
"foreignName" => "besturn",
"address" => "长春市",
"foundDate" => "2006-08-18",
"meaning" => "品质、性能、科技",
"scope" => "开发、制造、销售乘用车、发动机、变速箱及其配件。",
"staff" => "0",
"founder" => "郭力",
"slogan" => "进取不止",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-06-11 10:41:19",
"message" => "0",
"source" => "1",
"carscmsId" => "9",
"carscmsCountry" => "中国",
),
),
"L" => array
(
"0" => array
(
"id" => "61",
"brandName" => "力帆",
"logo" => "http://img.emao.net/car/logo/nd/bah/ncua.png",
"website" => "http://www.lifan.com/",
"firstWord" => "L",
"ssi" => "0",
"csi" => "0",
"classId" => "2",
"intro" => "重庆力帆实业(集团)公司成立于1992年，是中国最大的民营企业之一。历经21年发展，成为以汽车、摩托车的研发、生产、销售（包括出口）为主业，并投资于金融业的大型民营企业。2012年，力帆实业（集团）股份有限公司实现销售收入86.79亿元，产销汽车13.15万辆，出口创汇5.82亿美元，位列重庆民营企业第一位。截至2012年12月，累计申请专利8007件，其中已获授权专利6951件，各项指标居全国同行领先地位。目前，公司现有员工9375余名，其中具有大中专文化程度7080余人。力帆已十度入选中国企业500强，连续多年成为重庆市出口第一名。2010年11月25日，力帆股份在上海证券交易所成功上市，股票代码为601777，是中国首家上市A股的民营乘用车企。",
"companyName" => "重庆力帆实业（集团）公司",
"foreignName" => "lifan",
"address" => "",
"foundDate" => "0000-00-00",
"meaning" => "",
"scope" => "",
"staff" => "0",
"founder" => "",
"slogan" => "",
"story" => "",
"recommend" => "0",
"hot" => "0",
"hotRank" => "0",
"state" => "1",
"addtime" => "2014-10-21 01:07:36",
"updatetime" => "2015-03-26 19:12:34",
"message" => "0",
"source" => "1",
"carscmsId" => "62",
"carscmsCountry" => "中国",
),
),
),
"selling" => array
(
"0" => array
(
"id" => "1294",
"consumerId" => "23226",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "8",
"autoId" => "12828",
"smsTitle" => "整车中规车允许使用优惠券",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1438928044",
"updateTime" => "1438928093",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1438928074",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1438928078",
"backTime" => "",
"preSellTime" => "1438927200",
"sellTime" => "1438927200",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441432800",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "整车中规车允许使用优惠券",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "",
"finalTime" => "1441432800",
"sellLead" => "整车中规车允许使用优惠券",
"num" => "11",
"defemaoPrice" => "0.01",
"invoice" => "1",
"goodsCat" => "15",
"goodsType" => "1",
"salestate" => "",
"price" => "0.00",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪A4L",
"autoName" => "2015-df",
),
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "6",
"goodsName" => "2015-df lqx加的整车",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"tpl" => "1",
"multiple" => "0",
"sellTimeFormat" => "2015/08/07,14:00:00",
"endSellTimeFormat" => "2015/09/05,14:00:00",
"giftInfo" => array
(
"id" => "6",
"type" => "1",
"cover" => "/mall/nd/baf/jeqm.jpg",
"name" => "顶顶顶顶顶大大大",
"price" => "333",
"descr" => "天天天天天天天天天天天天",
"addTime" => "1428398967",
"addUser" => "root",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "1391",
"gid" => "1294",
"color" => "11",
"colorName" => "绿色",
"number" => "11",
"price" => "0.01",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "12828",
"autoName" => "df",
"displacement" => "1.0L",
"gearboxName" => "暂无",
"bodyConstruct" => "两厢",
"driveMode" => "暂无",
"officialOilWear" => "暂无",
"year" => "2015",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/dqsb.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/cyna.jpg",
"1" => "http://img.emao.net/mall/nd/bai/hdot.jpg",
"2" => "http://img.emao.net/mall/nd/bai/inxw.jpg",
),
),
"1" => array
(
"id" => "1291",
"consumerId" => "23226",
"sellType" => "2",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "1",
"smsTitle" => "",
"state" => "5",
"insertUser" => "mall@emao.com",
"insertTime" => "1438914952",
"updateTime" => "1438921273",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1438921248",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1438921252",
"backTime" => "",
"preSellTime" => "1438920000",
"sellTime" => "1438920000",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441425600",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "0",
"sortState" => "0",
"description" => "",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "666",
"finalTime" => "1440729000",
"sellLead" => "",
"num" => "132",
"defemaoPrice" => "0",
"invoice" => "0",
"goodsCat" => "19",
"goodsType" => "2",
"salestate" => "",
"price" => "368.80",
"autoName" => "",
"fullPayOn" => "0",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "wqqwwqwqwqwq",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"tpl" => "2",
"multiple" => "2",
"sellTimeFormat" => "2015/08/07,12:00:00",
"endSellTimeFormat" => "2015/09/05,12:00:00",
"couponInfo" => array
(
"id" => "140",
"gid" => "1291",
"sellPrice" => "0.01",
"faceValue" => "110000",
"couponDesc" => "",
),
"color" => array
(
),
"autoInfo" => array
(
"id" => "1",
"autoName" => "6.0L V11",
"displacement" => "6.0L",
"gearboxName" => "6挡手自一体",
"bodyConstruct" => "4门4座硬顶跑车",
"driveMode" => "前置后驱",
"officialOilWear" => "工信部未公布",
"year" => "2010",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/dkri.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/mgxv.jpg",
"1" => "http://img.emao.net/mall/nd/bai/ftgq.jpg",
"2" => "http://img.emao.net/mall/nd/bai/boez.jpg",
),
),
"2" => array
(
"id" => "1297",
"consumerId" => "23226",
"sellType" => "2",
"brandId" => "1",
"subBrandId" => "1",
"serieId" => "1",
"autoId" => "1",
"smsTitle" => "发送范德萨发生的",
"state" => "5",
"insertUser" => "mall@emao.com",
"insertTime" => "1438939672",
"updateTime" => "1438939723",
"submitUser" => "mall@emao.com",
"submitTime" => "1438939698",
"checkUser" => "mall@emao.com",
"checkTime" => "1438939704",
"backTime" => "",
"preSellTime" => "1438680600",
"sellTime" => "1438192800",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1441467000",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "26",
"sortState" => "26",
"description" => "发撒的发生发生的",
"isRefund" => "1",
"discountWay" => "1",
"discount" => "5000",
"contractNo" => "fdfasdfasfds",
"finalTime" => "1438939500",
"sellLead" => "风大时发生的发生的发生",
"num" => "349",
"defemaoPrice" => "950000",
"invoice" => "0",
"goodsCat" => "21",
"goodsType" => "1",
"salestate" => "",
"price" => "368.80",
"autoName" => array
(
"brandName" => "阿斯顿·马丁",
"subBrandName" => "阿斯顿·马丁",
"serieName" => "Rapide",
"autoName" => "2010-6.0L V11",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"ticketCount" => "3",
"goodsName" => "zgl整车中规车",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"tpl" => "1",
"multiple" => "0",
"sellTimeFormat" => "2015/07/30,02:00:00",
"endSellTimeFormat" => "2015/09/05,23:30:00",
"giftInfo" => array
(
"id" => "11",
"type" => "1",
"cover" => "/mall/nd/bak/gsus.jpg",
"name" => "天热委托人",
"price" => "54354",
"descr" => "77777777777777",
"addTime" => "1431076116",
"addUser" => "mall@emao.com",
"state" => "1",
"typeName" => "加油卡",
),
"color" => array
(
"0" => array
(
"id" => "1392",
"gid" => "1297",
"color" => "1",
"colorName" => "亚光黑",
"number" => "90",
"price" => "990000",
"sold" => "0",
"isOnSell" => "1",
),
"1" => array
(
"id" => "1393",
"gid" => "1297",
"color" => "6",
"colorName" => "大红色",
"number" => "80",
"price" => "980000",
"sold" => "0",
"isOnSell" => "1",
),
"2" => array
(
"id" => "1394",
"gid" => "1297",
"color" => "11",
"colorName" => "绿色",
"number" => "70",
"price" => "970000",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "1395",
"gid" => "1297",
"color" => "16",
"colorName" => "紫色",
"number" => "60",
"price" => "960000",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "1396",
"gid" => "1297",
"color" => "21",
"colorName" => "粉色",
"number" => "49",
"price" => "950000",
"sold" => "1",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "1",
"autoName" => "6.0L V11",
"displacement" => "6.0L",
"gearboxName" => "6挡手自一体",
"bodyConstruct" => "4门4座硬顶跑车",
"driveMode" => "前置后驱",
"officialOilWear" => "工信部未公布",
"year" => "2010",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/mzes.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/desa.jpg",
"1" => "http://img.emao.net/mall/nd/bai/nfgf.jpg",
"2" => "http://img.emao.net/mall/nd/bai/ecxu.jpg",
),
),
"3" => array
(
"id" => "1293",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "2",
"serieId" => "10",
"autoId" => "116",
"smsTitle" => "eve-整车中规车-限时抢购eve-整车中规车-限时抢购",
"state" => "5",
"insertUser" => "root",
"insertTime" => "1438926146",
"updateTime" => "1438927104",
"submitUser" => "root",
"submitTime" => "1438926910",
"checkUser" => "root",
"checkTime" => "1438926928",
"backTime" => "",
"preSellTime" => "1438925400",
"sellTime" => "1438927200",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1439011800",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "28",
"sortState" => "28",
"description" => "eve-整车中规车-限时抢购eve-整车中规车-限时抢购eve-整车中规车-限时抢购eve-整车中规车-限时抢购eve-整车中规车-限时抢购",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "eve001",
"finalTime" => "1438961400",
"sellLead" => "eve-整车中规车-限时抢购",
"num" => "10",
"defemaoPrice" => "100000",
"invoice" => "1",
"goodsCat" => "15",
"goodsType" => "1",
"salestate" => "",
"price" => "35.85",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "一汽奥迪",
"serieName" => "奥迪Q5",
"autoName" => "2015-35 TFSI 标准型",
),
"fullPayOn" => "1",
"isPurchase" => "1",
"ticketCount" => "0",
"goodsName" => "2015-35 TFSI 标准型",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"tpl" => "1",
"multiple" => "0",
"sellTimeFormat" => "2015/08/07,14:00:00",
"endSellTimeFormat" => "2015/08/08,13:30:00",
"giftInfo" => array
(
),
"color" => array
(
"0" => array
(
"id" => "1390",
"gid" => "1293",
"color" => "1",
"colorName" => "幻影黑",
"number" => "10",
"price" => "100000",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "116",
"autoName" => "35 TFSI 标准型",
"displacement" => "2.0T",
"gearboxName" => "6挡手动",
"bodyConstruct" => "5门5座SUV",
"driveMode" => "前置四驱",
"officialOilWear" => "8.2L/100KM",
"year" => "2015",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/jaci.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/bugr.jpg",
"1" => "http://img.emao.net/mall/nd/bai/nrhy.jpg",
"2" => "http://img.emao.net/mall/nd/bai/luvr.jpg",
),
),
"4" => array
(
"id" => "1292",
"consumerId" => "23202",
"sellType" => "2",
"brandId" => "2",
"subBrandId" => "3",
"serieId" => "15",
"autoId" => "160",
"smsTitle" => "EDM/短信标题",
"state" => "5",
"insertUser" => "liqiaoxia381@emao.com",
"insertTime" => "1438920131",
"updateTime" => "1438920639",
"submitUser" => "liqiaoxia381@emao.com",
"submitTime" => "1438920615",
"checkUser" => "liqiaoxia381@emao.com",
"checkTime" => "1438920622",
"backTime" => "",
"preSellTime" => "1438920000",
"sellTime" => "1438920000",
"underUser" => "",
"underTxt" => "",
"under" => "1",
"endSellTime" => "1440734400",
"endSellCount" => "0",
"isDel" => "0",
"delUser" => "",
"delTime" => "",
"sort" => "37",
"sortState" => "37",
"description" => "商品描述：",
"isRefund" => "1",
"discountWay" => "0",
"discount" => "0",
"contractNo" => "12345678900987654321",
"finalTime" => "1440732600",
"sellLead" => "售卖导语：",
"num" => "143",
"defemaoPrice" => "110000",
"invoice" => "1",
"goodsCat" => "15",
"goodsType" => "1",
"salestate" => "",
"price" => "29.98",
"autoName" => array
(
"brandName" => "奥迪",
"subBrandName" => "奥迪(进口)",
"serieName" => "奥迪A1",
"autoName" => "2014-30 TFSI Sportback豪华型",
),
"fullPayOn" => "1",
"isPurchase" => "0",
"ticketCount" => "0",
"goodsName" => "2014-30 TFSI Sportback豪华型lqx加的",
"stockType" => "1",
"isTest" => "2",
"bargainType" => "1",
"tpl" => "2",
"multiple" => "1",
"sellTimeFormat" => "2015/08/07,12:00:00",
"endSellTimeFormat" => "2015/08/28,12:00:00",
"couponInfo" => array
(
"id" => "1377",
"gid" => "1292",
"sellPrice" => "0.01",
"faceValue" => "5000",
"couponDesc" => "",
),
"giftInfo" => array
(
),
"color" => array
(
"0" => array
(
"id" => "1377",
"gid" => "1292",
"color" => "1",
"colorName" => "幻影黑",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"1" => array
(
"id" => "1378",
"gid" => "1292",
"color" => "2",
"colorName" => "旋风黑色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"2" => array
(
"id" => "1379",
"gid" => "1292",
"color" => "4",
"colorName" => "天云灰色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"3" => array
(
"id" => "1380",
"gid" => "1292",
"color" => "5",
"colorName" => "冰川白色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"4" => array
(
"id" => "1381",
"gid" => "1292",
"color" => "6",
"colorName" => "米萨诺红色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"5" => array
(
"id" => "1382",
"gid" => "1292",
"color" => "7",
"colorName" => "西拉红色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"6" => array
(
"id" => "1383",
"gid" => "1292",
"color" => "9",
"colorName" => "柚木棕",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"7" => array
(
"id" => "1384",
"gid" => "1292",
"color" => "13",
"colorName" => "积云蓝色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"8" => array
(
"id" => "1385",
"gid" => "1292",
"color" => "14",
"colorName" => "思科巴蓝",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"9" => array
(
"id" => "1386",
"gid" => "1292",
"color" => "15",
"colorName" => "星球蓝色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"10" => array
(
"id" => "1387",
"gid" => "1292",
"color" => "17",
"colorName" => "萨摩亚橙色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"11" => array
(
"id" => "1388",
"gid" => "1292",
"color" => "18",
"colorName" => "阿玛菲白色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
"12" => array
(
"id" => "1389",
"gid" => "1292",
"color" => "19",
"colorName" => "水晶银色",
"number" => "11",
"price" => "110000",
"sold" => "0",
"isOnSell" => "1",
),
),
"autoInfo" => array
(
"id" => "160",
"autoName" => "30 TFSI Sportback豪华型",
"displacement" => "1.4T",
"gearboxName" => "7挡双离合",
"bodyConstruct" => "5门4座两厢车",
"driveMode" => "前置前驱",
"officialOilWear" => "5.5L/100KM",
"year" => "2014",
),
"mainImg" => "http://img.emao.net/mall/nd/bai/ejel.jpg",
"secImg" => array
(
"0" => "http://img.emao.net/mall/nd/bai/fhkm.jpg",
"1" => "http://img.emao.net/mall/nd/bai/dkyf.jpg",
"2" => "http://img.emao.net/mall/nd/bai/gllq.jpg",
),
),
),
"willSell" => array
(
),
"pageTitle" => "北京汽车商城_北京特价车_北京网购汽车_一猫商城",
"pageKeyword" => "北京网购汽车,北京买车,北京汽车报价,北京特价车",
"pageDescription" => "北京汽车商城是一猫电商在线买车平台，一猫汽车商城提供北京汽车价格、图片、买车、使用等务信息，北京汽车网报价大全。",
"__loginInfo" => array
(
"id" => "298",
"username" => "fuwei119",
"nickname" => "Henry",
"realname" => "",
"pwd" => "21232f297a57a5a743894a0e4a801fc3",
"birthday" => "0000-01-00",
"sex" => "-1",
"selfintro" => "",
"phone" => "18610659529",
"phoneValid" => "18610659529",
"mail" => "fuwei119@emao.com",
"mailValid" => "",
"nation_id" => "0",
"province_id" => "0",
"city_id" => "0",
"district_id" => "0",
"major" => "",
"mood" => "",
"tags" => "",
"head_img_uri" => "http://s.emao.net/images/common/uc_user_avatar.png",
"role" => "0",
"regIP" => "",
"login_time" => "2015-08-07 17:52:53",
"reg_time" => "2014-10-22 17:48:09",
"update_time" => "2015-08-07 17:52:53",
"completeStatus" => "4",
"status" => "1",
"source" => "0",
"client" => "0",
"auditStatus" => "1",
"usernameSetted" => "0",
"nicknameSetted" => "0",
"passwordSetted" => "1",
"head_img_url" => "http://s.emao.net/images/common/uc_user_avatar.png",
"avatarSetted" => "0",
"avatar" => "http://s.emao.net/images/common/uc_user_avatar.png",
),
"__serverTime" => "1438941288",
"__serverTimeFormat" => "2015/08/07,17:54:48",
"__openCity" => array
(
"1" => array
(
"cityId" => "1",
"cityName" => "北京",
"pinyin" => "beijing",
"isOpen" => "1",
"insertUser" => "liukang317@emao.com",
"userId" => "90",
"addTime" => "1433153262",
),
"2" => array
(
"cityId" => "2",
"cityName" => "天津",
"pinyin" => "tianjin",
"isOpen" => "1",
"insertUser" => "mall@emao.com",
"userId" => "97",
"addTime" => "1430822126",
),
"169" => array
(
"cityId" => "169",
"cityName" => "武汉",
"pinyin" => "wuhan",
"isOpen" => "1",
"insertUser" => "root",
"userId" => "1",
"addTime" => "1437037629",
),
),
"__http" => array
(
"tejia" => "http://tejia.emao.com",
"tejia_m" => "http://tejia.m.emao.com",
"i" => "http://i.emao.com",
"i_m" => "http://i.m.emao.com",
),
),
);