<?php 
$fis_data=
array
(
"tplData"=>array
(
"openCity"=>array
(
"0"=>array
(
"provinceName"=>"直辖市",
"citys"=>array
(
"0"=>array
(
"cityId"=>1,
"provinceId"=>1,
"provinceName"=>"北京",
"cityName"=>"北京",
"pinyin"=>"beijing",
"isOpen"=>1,
"isHot"=>"0",
"insertUser"=>"liqiaoxia381@emao.com",
"userId"=>105,
"addTime"=>1443074313,
),

"1"=>array
(
"cityId"=>2,
"provinceId"=>2,
"provinceName"=>"天津",
"cityName"=>"天津",
"pinyin"=>"tianjin",
"isOpen"=>1,
"isHot"=>1,
"insertUser"=>"root",
"userId"=>1,
"addTime"=>1441176992,
),

),

),

"3"=>array
(
"provinceName"=>"河北",
"citys"=>array
(
"0"=>array
(
"cityId"=>3,
"provinceId"=>3,
"provinceName"=>"河北",
"cityName"=>"石家庄",
"pinyin"=>"shijiazhuang",
"isOpen"=>1,
"isHot"=>1,
"insertUser"=>"root",
"userId"=>1,
"addTime"=>1431416378,
),

),

),

"27"=>array
(
"provinceName"=>"陕西",
"citys"=>array
(
"0"=>array
(
"cityId"=>288,
"provinceId"=>27,
"provinceName"=>"陕西",
"cityName"=>"西安",
"pinyin"=>"xian",
"isOpen"=>1,
"isHot"=>"0",
"insertUser"=>"root",
"userId"=>1,
"addTime"=>1445833237,
),

),

),

),

"curCity"=>array
(
"cityId"=>1,
"provinceId"=>1,
"provinceName"=>"北京",
"cityName"=>"北京",
"pinyin"=>"beijing",
"isOpen"=>1,
"isHot"=>"0",
"insertUser"=>"liqiaoxia381@emao.com",
"userId"=>105,
"addTime"=>1443074313,
),

"hotCity"=>array
(
"0"=>array
(
"cityId"=>2,
"provinceId"=>2,
"provinceName"=>"天津",
"cityName"=>"天津",
"pinyin"=>"tianjin",
"isOpen"=>1,
"isHot"=>1,
"insertUser"=>"root",
"userId"=>1,
"addTime"=>1441176992,
),

"1"=>array
(
"cityId"=>3,
"provinceId"=>3,
"provinceName"=>"河北",
"cityName"=>"石家庄",
"pinyin"=>"shijiazhuang",
"isOpen"=>1,
"isHot"=>1,
"insertUser"=>"root",
"userId"=>1,
"addTime"=>1431416378,
),

),

"priceList"=>array
(
"1"=>"5万以下",
"2"=>"5-8万",
"4"=>"8-12万",
"8"=>"12-18万",
"16"=>"18-25万",
"32"=>"25-30万",
"64"=>"30-50万",
"128"=>"50万以上",
),

"carriageList"=>array
(
"2"=>"两厢",
"4"=>"三厢",
"8"=>"SUV",
"16"=>"MPV",
"256"=>"微客",
"2048"=>"新能源",
),

"onlineTalkUri"=>"<br/>local Test<br/>",
"allBrandList"=>array
(
"A"=>array
(
"0"=>array
(
"id"=>1,
"brandName"=>"阿斯顿·马丁",
"logo"=>"http://img.emao.net/car/logo/nd/bah/oxp.png",
"website"=>"http://www.astonmartin-china.com",
"firstWord"=>"A",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"阿斯顿·马丁",
"foreignName"=>"Aston Martin",
"address"=>"英国盖顿",
"foundDate"=>"0000-00-00",
"meaning"=>"阿斯顿·马丁汽车标志为一只展翅飞翔的大鹏，喻示该公司像大鹏鸟一样，具有从天而降的冲刺速度和远大的志向。",
"scope"=>"高端赛车、跑车、敞篷旅行车",
"staff"=>"0",
"founder"=>"莱昂内尔·马丁、罗伯特·班福德",
"slogan"=>"",
"story"=>"",
"recommend"=>1,
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-07-21 11:05:04",
"message"=>"0",
"source"=>1,
"carscmsId"=>1,
"carscmsCountry"=>"英国",
"sort"=>"",
),

),

"B"=>array
(
"0"=>array
(
"id"=>6,
"brandName"=>"保时捷",
"logo"=>"http://img.emao.net/car/logo/nd/bah/kvmy.png",
"website"=>"http://www.porsche.com/china/",
"firstWord"=>"B",
"ssi"=>"0",
"csi"=>"0",
"classId"=>3,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"德国保时捷公司",
"foreignName"=>"Porsche",
"address"=>"德国斯图加特",
"foundDate"=>"1931-04-25",
"meaning"=>"通过一幅优美的田园风景画，展现了保时捷公司辉煌的过去，预示了美好的未来及保时捷跑车的出类拔萃。",
"scope"=>"高端汽车的开发、生产、营销",
"staff"=>"0",
"founder"=>"费迪南德·保时捷",
"slogan"=>"There Is No Substitute（无可替代）",
"story"=>"",
"recommend"=>1,
"hot"=>1,
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-06-12 11:08:32",
"message"=>"0",
"source"=>1,
"carscmsId"=>6,
"carscmsCountry"=>"德国",
"sort"=>"",
),

"1"=>array
(
"id"=>8,
"brandName"=>"奔驰",
"logo"=>"http://img.emao.net/car/logo/nd/bah/hboc.png",
"website"=>"http://www.mercedes-benz.com.cn",
"firstWord"=>"B",
"ssi"=>"0",
"csi"=>"0",
"classId"=>3,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"梅赛德斯-奔驰",
"foreignName"=>"Mercedes-Benz",
"address"=>"德国斯图加特",
"foundDate"=>"1900-12-22",
"meaning"=>"奔驰的三叉星象征着征服陆、海、空的愿望。",
"scope"=>"豪华轿车、客车、卡车、跑车",
"staff"=>"0",
"founder"=>"卡尔·本茨、戈特利布·戴姆勒",
"slogan"=>"Das Beste Oder Nichts（惟有最好）",
"story"=>"",
"recommend"=>"0",
"hot"=>1,
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-07-23 14:35:47",
"message"=>"0",
"source"=>1,
"carscmsId"=>8,
"carscmsCountry"=>"德国",
"sort"=>"",
),

"2"=>array
(
"id"=>7,
"brandName"=>"北汽制造",
"logo"=>"http://img.emao.net/car/logo/nd/bah/kjjx.png",
"website"=>"http://www.baw.com.cn/home.html",
"firstWord"=>"B",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"北京汽车制造厂",
"foreignName"=>"beijingqichezhizaochang",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:28:03",
"message"=>"0",
"source"=>1,
"carscmsId"=>7,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"3"=>array
(
"id"=>4,
"brandName"=>"宝骏",
"logo"=>"http://img.emao.net/car/logo/nd/bah/oikc.png",
"website"=>"http://www.autobaojun.com/",
"firstWord"=>"B",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"上海通用",
"foreignName"=>"shanghaitongyong",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>1,
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-06-10 17:18:55",
"message"=>"0",
"source"=>1,
"carscmsId"=>4,
"carscmsCountry"=>"自主",
"sort"=>10,
),

"4"=>array
(
"id"=>13,
"brandName"=>"别克",
"logo"=>"http://img.emao.net/car/logo/nd/bah/gvmt.png",
"website"=>"http://www.buick.com.cn/",
"firstWord"=>"B",
"ssi"=>"0",
"csi"=>15,
"classId"=>2,
"intro"=>"别克（Buick），是由美国通用汽车公司在美国、加拿大和中国创立的一个品牌。它在北美、中国、独联体国家以及中东都有销售。",
"companyName"=>"别克汽车公司",
"foreignName"=>"BUICK",
"address"=>"美国",
"foundDate"=>"1904-05-14",
"meaning"=>"象征着一种积极进取，不断登攀的精神。",
"scope"=>"中高端汽车生产",
"staff"=>"0",
"founder"=>"大卫 ·邓巴· 别克",
"slogan"=>"用心超越，品味无限。",
"story"=>"",
"recommend"=>"0",
"hot"=>1,
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-07-23 14:36:16",
"message"=>"0",
"source"=>1,
"carscmsId"=>13,
"carscmsCountry"=>"美国",
"sort"=>10,
),

"5"=>array
(
"id"=>15,
"brandName"=>"布加迪",
"logo"=>"http://img.emao.net/car/logo/nd/bah/lany.png",
"website"=>"http://www.bugatti.com/en/home.html",
"firstWord"=>"B",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"布加迪汽车公司",
"foreignName"=>"Bugatti Automobili SA",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:36:13",
"message"=>"0",
"source"=>1,
"carscmsId"=>15,
"carscmsCountry"=>"法国",
"sort"=>"",
),

"6"=>array
(
"id"=>14,
"brandName"=>"宾利",
"logo"=>"http://img.emao.net/car/logo/nd/bap/fwex.png",
"website"=>"http://www.bentleymotors.com/",
"firstWord"=>"B",
"ssi"=>"0",
"csi"=>"0",
"classId"=>3,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"宾利汽车股份有限公司",
"foreignName"=>"Bentley",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:34:14",
"message"=>"0",
"source"=>1,
"carscmsId"=>14,
"carscmsCountry"=>"英国",
"sort"=>"",
),

),

"C"=>array
(
"0"=>array
(
"id"=>18,
"brandName"=>"长城",
"logo"=>"http://img.emao.net/car/logo/nd/bah/lgqk.png",
"website"=>"http://www.gwm.com.cn/",
"firstWord"=>"C",
"ssi"=>"0",
"csi"=>"0",
"classId"=>1,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"保定长城汽车股份有限公司",
"foreignName"=>"Great Wall Motor",
"address"=>"河北省保定市",
"foundDate"=>"1984-10-28",
"meaning"=>"椭圆外形：立足中国、走向世界；烽火台形象：中国传统文化象征；剑锋箭头：充满活力、蒸蒸日上，敢于亮剑、无坚不摧；立体“1”",
"scope"=>"皮卡、SUV专业厂。",
"staff"=>"0",
"founder"=>"",
"slogan"=>"每天进步一点点",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:40:31",
"message"=>"0",
"source"=>1,
"carscmsId"=>18,
"carscmsCountry"=>"中国",
"sort"=>"",
),

),

"D"=>array
(
"0"=>array
(
"id"=>21,
"brandName"=>"大众",
"logo"=>"http://img.emao.net/car/logo/nd/bah/kcix.png",
"website"=>"http://www.vw.com.cn/",
"firstWord"=>"D",
"ssi"=>5,
"csi"=>14,
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"大众汽车集团",
"foreignName"=>"Volkswagen",
"address"=>"沃尔夫斯堡",
"foundDate"=>"1937-03-28",
"meaning"=>"标志象是由三个用中指和食指作出的“V”组成，表示大众公司及其产品必胜－必胜－必胜。",
"scope"=>"汽车、金融",
"staff"=>"0",
"founder"=>"阿道夫·希特勒、费迪南德.保时捷",
"slogan"=>"车之道，唯大众",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:42:26",
"message"=>"0",
"source"=>1,
"carscmsId"=>21,
"carscmsCountry"=>"德国",
"sort"=>"",
),

"1"=>array
(
"id"=>23,
"brandName"=>"帝豪",
"logo"=>"http://img.emao.net/car/logo/nd/bah/ffcn.png",
"website"=>"http://www.dhcar.cn/",
"firstWord"=>"D",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"吉利汽车",
"foreignName"=>"jiliqiche",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>"0",
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:44:01",
"message"=>"0",
"source"=>1,
"carscmsId"=>23,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"2"=>array
(
"id"=>24,
"brandName"=>"东风",
"logo"=>"http://img.emao.net/car/logo/nd/bah/nvha.png",
"website"=>"",
"firstWord"=>"D",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"东风所属一汽公司，于1958年5月5日生产，东风的生产毛主席都为之骄傲，东风轿车的诞生，使我们中华民族结束了一个历史，又创造了一个历史。",
"companyName"=>"东风汽车公司",
"foreignName"=>"Dongfeng Motor Corporation",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:44:19",
"message"=>"0",
"source"=>1,
"carscmsId"=>24,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"3"=>array
(
"id"=>26,
"brandName"=>"东风小康",
"logo"=>"http://img.emao.net/car/logo/nd/bah/bgbw.png",
"website"=>"http://www.dfyuan.com/index.php",
"firstWord"=>"D",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"东风渝安车辆有限公司",
"foreignName"=>"dongfengyuancheliangyouxiangongsi",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:45:42",
"message"=>"0",
"source"=>1,
"carscmsId"=>26,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"4"=>array
(
"id"=>27,
"brandName"=>"东南",
"logo"=>"http://img.emao.net/car/logo/nd/bah/lyur.png",
"website"=>"http://www.soueast-motor.com/index.do?act=product&todo=dn",
"firstWord"=>"D",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"东南（福建）汽车工业有限公司",
"foreignName"=>"Soueast Motor",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:46:15",
"message"=>"0",
"source"=>1,
"carscmsId"=>27,
"carscmsCountry"=>"中国",
"sort"=>"",
),

"5"=>array
(
"id"=>22,
"brandName"=>"道奇",
"logo"=>"http://img.emao.net/car/logo/nd/baz/hptv.png",
"website"=>"http://www.dodge.cn",
"firstWord"=>"D",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"“道奇”文字商标采用道奇兄弟的姓氏“Dodge”，图形商标是在一个五边形中有一羊头形象，在汽车上使用小公羊、大公羊两个商标。",
"companyName"=>"道奇公司",
"foreignName"=>"Dodge",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:43:23",
"message"=>"0",
"source"=>1,
"carscmsId"=>22,
"carscmsCountry"=>"美国",
"sort"=>"",
),

),

"F"=>array
(
"0"=>array
(
"id"=>28,
"brandName"=>"法拉利",
"logo"=>"http://img.emao.net/car/logo/nd/bah/mkwg.png",
"website"=>"",
"firstWord"=>"F",
"ssi"=>"0",
"csi"=>"0",
"classId"=>3,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"法拉利汽车公司",
"foreignName"=>"Ferrari",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-06-10 17:11:06",
"message"=>"0",
"source"=>1,
"carscmsId"=>28,
"carscmsCountry"=>"意大利",
"sort"=>"",
),

"1"=>array
(
"id"=>29,
"brandName"=>"菲亚特",
"logo"=>"http://img.emao.net/car/logo/nd/bah/flcd.png",
"website"=>"http://www.fiat.com.cn/",
"firstWord"=>"F",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"菲亚特",
"foreignName"=>"FIAT",
"address"=>"意大利都灵",
"foundDate"=>"0000-00-00",
"meaning"=>"Fabbrica Italiana Automobile Torino的首字母组成。",
"scope"=>"汽车制造",
"staff"=>"0",
"founder"=>"乔瓦尼.阿涅利",
"slogan"=>"人生如此美丽",
"story"=>"",
"recommend"=>1,
"hot"=>1,
"hotRank"=>8,
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:52:34",
"message"=>"0",
"source"=>1,
"carscmsId"=>29,
"carscmsCountry"=>"意大利",
"sort"=>"",
),

"2"=>array
(
"id"=>31,
"brandName"=>"福迪",
"logo"=>"http://img.emao.net/car/logo/nd/bah/obgz.png",
"website"=>"http://www.fdqc.com/",
"firstWord"=>"F",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"福迪汽车",
"foreignName"=>"fudiqiche",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:53:58",
"message"=>"0",
"source"=>1,
"carscmsId"=>31,
"carscmsCountry"=>"中国",
"sort"=>"",
),

"3"=>array
(
"id"=>32,
"brandName"=>"福特",
"logo"=>"http://img.emao.net/car/logo/nd/bah/irva.png",
"website"=>"http://www.ford.com.cn",
"firstWord"=>"F",
"ssi"=>6,
"csi"=>16,
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"福特汽车公司",
"foreignName"=>"Ford",
"address"=>"美国 密歇根州 迪尔伯恩",
"foundDate"=>"1903-06-16",
"meaning"=>"Ford犹如在温馨的大自然中，有一只可爱，温顺的小白兔正在向前飞奔，象征福特汽车奔驰在世界各地，令人爱不释手。",
"scope"=>"中端汽车生产",
"staff"=>"0",
"founder"=>"亨利·福特",
"slogan"=>"福特、进无止境",
"story"=>"",
"recommend"=>1,
"hot"=>1,
"hotRank"=>5,
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:54:19",
"message"=>"0",
"source"=>1,
"carscmsId"=>32,
"carscmsCountry"=>"美国",
"sort"=>"",
),

"4"=>array
(
"id"=>33,
"brandName"=>"福田",
"logo"=>"http://img.emao.net/car/logo/nd/bah/kulr.png",
"website"=>"http://www.foton.com.cn/",
"firstWord"=>"F",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"北汽福田汽车股份有限公司",
"foreignName"=>"beiqifutian",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:54:48",
"message"=>"0",
"source"=>1,
"carscmsId"=>33,
"carscmsCountry"=>"中国",
"sort"=>"",
),

),

"G"=>array
(
"0"=>array
(
"id"=>36,
"brandName"=>"广汽传祺",
"logo"=>"http://img.emao.net/car/logo/nd/bah/jwey.png",
"website"=>"http://www.gacmotor.com/",
"firstWord"=>"G",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"广州汽车集团股份有限公司",
"foreignName"=>"Guangzhou Automobile Group Co., Ltd.",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:56:36",
"message"=>"0",
"source"=>1,
"carscmsId"=>36,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"1"=>array
(
"id"=>44,
"brandName"=>"广汽吉奥",
"logo"=>"http://img.emao.net/car/logo/nd/bah/ohiv.png",
"website"=>"http://www.gonowauto.com",
"firstWord"=>"G",
"ssi"=>"0",
"csi"=>"0",
"classId"=>1,
"intro"=>"广汽吉奥汽车有限公司成立于2010年12月9日，是吉奥汽车与广汽集团在杭州签约成立的新的合资公司，是国内先进的皮卡生产基地和微型客车生产基地。",
"companyName"=>"吉奥汽车",
"foreignName"=>"jiaoqiche",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:56:59",
"message"=>"0",
"source"=>1,
"carscmsId"=>44,
"carscmsCountry"=>"自主",
"sort"=>"",
),

),

"H"=>array
(
"0"=>array
(
"id"=>37,
"brandName"=>"哈飞",
"logo"=>"http://img.emao.net/car/logo/nd/bah/lsrm.png",
"website"=>"http://www.hafeiauto.com.cn/",
"firstWord"=>"H",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"哈尔滨哈飞汽车工业集团有限公司",
"foreignName"=>"HARBIN HAFEI AUTOMOBILE INDUSTRY GROUP CO.,LTD",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:57:50",
"message"=>"0",
"source"=>1,
"carscmsId"=>37,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"1"=>array
(
"id"=>38,
"brandName"=>"海格",
"logo"=>"http://img.emao.net/car/logo/nd/bah/cwlb.png",
"website"=>"http://car.higer.cn",
"firstWord"=>"H",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"海格",
"foreignName"=>"haige",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:58:05",
"message"=>"0",
"source"=>1,
"carscmsId"=>38,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"2"=>array
(
"id"=>39,
"brandName"=>"海马",
"logo"=>"http://img.emao.net/car/logo/nd/bah/zyq.png",
"website"=>"http://www.haima.com/",
"firstWord"=>"H",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"海马汽车",
"foreignName"=>"FAW Haima Automobile",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 18:58:26",
"message"=>"0",
"source"=>1,
"carscmsId"=>39,
"carscmsCountry"=>"自主",
"sort"=>"",
),

),

"J"=>array
(
"0"=>array
(
"id"=>45,
"brandName"=>"江淮",
"logo"=>"http://img.emao.net/car/logo/nd/bah/niqy.png",
"website"=>"http://www.jac.com.cn",
"firstWord"=>"J",
"ssi"=>"0",
"csi"=>"0",
"classId"=>1,
"intro"=>"安徽江淮汽车股份有限公司的前身为合肥江淮汽车制造厂，始建于1964年。公司占地面积460多万平方米，总资产53亿元。",
"companyName"=>"安徽江淮汽车股份有限公司",
"foreignName"=>"JAC",
"address"=>"安徽合肥",
"foundDate"=>"1999-09-30",
"meaning"=>"柔和与刚毅兼具，稳重而极具张力，充分辉映着“制造更好的产 品，创造更美好的社会”的江淮汽车的企业愿景。",
"scope"=>"汽车制造商",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:02:59",
"message"=>"0",
"source"=>1,
"carscmsId"=>46,
"carscmsCountry"=>"中国",
"sort"=>"",
),

"1"=>array
(
"id"=>48,
"brandName"=>"金杯",
"logo"=>"http://img.emao.net/car/logo/nd/bah/onnv.png",
"website"=>"http://www.jinbei.com.cn/jinbei/index.aspx",
"firstWord"=>"J",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"公司是华晨汽车集团所属的金杯汽车股份有限公司控股的国内主要卡车生产厂之一，于1958年建厂，具有悠久的发展历史，2002年由沈阳汽车制造厂重组为沈阳金杯车辆制造有限公司。",
"companyName"=>"金杯汽车股份有限公司",
"foreignName"=>"jinbeiqiche",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:04:07",
"message"=>"0",
"source"=>1,
"carscmsId"=>49,
"carscmsCountry"=>"中国",
"sort"=>"",
),

"2"=>array
(
"id"=>49,
"brandName"=>"九龙",
"logo"=>"http://img.emao.net/car/logo/nd/bah/ohme.png",
"website"=>"http://www.joylong.net/Simplified/index.asp",
"firstWord"=>"J",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"九龙汽车是江苏著名汽车品牌，产品以其出色的质量和稳固的性能远销海内外42个国家和地区；九龙汽车在外观、空间、内饰、配置、安全及动力等多方面",

"companyName"=>"江苏九龙汽车制造有限公司",
"foreignName"=>"jiulongqiche",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:04:26",
"message"=>"0",
"source"=>1,
"carscmsId"=>50,
"carscmsCountry"=>"中国",
"sort"=>10,
),

),

"K"=>array
(
"0"=>array
(
"id"=>50,
"brandName"=>"卡尔森",
"logo"=>"http://img.emao.net/car/logo/nd/bah/oazv.png",
"website"=>"http://www.carlssonsh.com/",
"firstWord"=>"K",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"卡尔森汽车始建于1989年，是一家拥有独立品牌的汽车生产公司。",
"companyName"=>"卡尔森汽车",
"foreignName"=>"Carlsson",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>"0",
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:06:16",
"message"=>"0",
"source"=>1,
"carscmsId"=>51,
"carscmsCountry"=>"德国",
"sort"=>"",
),

"1"=>array
(
"id"=>51,
"brandName"=>"开瑞",
"logo"=>"http://img.emao.net/car/logo/nd/bah/jvya.png",
"website"=>"http://www.karryauto.cn/",
"firstWord"=>"K",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"开瑞品牌为奇瑞公司于2009年1月12日推出的全新高性能微型车品牌。",
"companyName"=>"奇瑞",
"foreignName"=>"Chery",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:06:55",
"message"=>"0",
"source"=>1,
"carscmsId"=>52,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"2"=>array
(
"id"=>52,
"brandName"=>"凯迪拉克",
"logo"=>"http://img.emao.net/car/logo/nd/bah/htkf.png",
"website"=>"http://www.cadillac.com.cn/",
"firstWord"=>"K",
"ssi"=>"0",
"csi"=>"0",
"classId"=>3,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"凯迪拉克汽车公司",
"foreignName"=>"Cadillac",
"address"=>"美国",
"foundDate"=>"1902-10-17",
"meaning"=>"象征凯迪拉克皇家贵族的金戈铁马，骁勇善战",
"scope"=>"高端汽车生产",
"staff"=>"0",
"founder"=>"亨利·利兰",
"slogan"=>"敢为天下先",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:07:21",
"message"=>"0",
"source"=>1,
"carscmsId"=>53,
"carscmsCountry"=>"美国",
"sort"=>"",
),

"3"=>array
(
"id"=>53,
"brandName"=>"科尼赛克",
"logo"=>"http://img.emao.net/car/logo/nd/bah/mqkk.png",
"website"=>"http://www.koenigsegg.se",
"firstWord"=>"K",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"科尼赛克",
"foreignName"=>"Koenigsegg",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:07:55",
"message"=>"0",
"source"=>1,
"carscmsId"=>54,
"carscmsCountry"=>"瑞典",
"sort"=>"",
),

),

"L"=>array
(
"0"=>array
(
"id"=>55,
"brandName"=>"兰博基尼",
"logo"=>"http://img.emao.net/car/logo/nd/bah/cdzb.png",
"website"=>"http://www.lamborghini.com/",
"firstWord"=>"L",
"ssi"=>"0",
"csi"=>"0",
"classId"=>3,
"intro"=>"<br/>local Test<br/>",

"companyName"=>"兰博基尼汽车公司",
"foreignName"=>"Automobili Lamborghini S.p.A",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:10:01",
"message"=>"0",
"source"=>1,
"carscmsId"=>56,
"carscmsCountry"=>"意大利",
"sort"=>"",
),

"1"=>array
(
"id"=>61,
"brandName"=>"力帆",
"logo"=>"http://img.emao.net/car/logo/nd/bah/ncua.png",
"website"=>"http://www.lifan.com/",
"firstWord"=>"L",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"重庆力帆实业（集团）公司",
"foreignName"=>"lifan",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:12:34",
"message"=>"0",
"source"=>1,
"carscmsId"=>62,
"carscmsCountry"=>"中国",
"sort"=>2,
),

"2"=>array
(
"id"=>62,
"brandName"=>"莲花汽车",
"logo"=>"http://img.emao.net/car/logo/nd/bah/noxd.png",
"website"=>"http://www.youngmanlotus.com/",
"firstWord"=>"L",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"青年汽车集团",
"foreignName"=>"lianhuaqiche",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:12:50",
"message"=>"0",
"source"=>1,
"carscmsId"=>63,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"3"=>array
(
"id"=>19,
"brandName"=>"猎豹汽车",
"logo"=>"http://img.emao.net/car/logo/nd/bah/ilxz.png",
"website"=>"http://www.cfmotors.com/",
"firstWord"=>"L",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"广汽长丰汽车股份有限公司",
"foreignName"=>"guangqichangfengqichegu",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:09:40",
"message"=>"0",
"source"=>1,
"carscmsId"=>19,
"carscmsCountry"=>"自主",
"sort"=>"",
),

"4"=>array
(
"id"=>56,
"brandName"=>"劳伦士",
"logo"=>"http://img.emao.net/car/logo/nd/bah/ilin.png",
"website"=>"http://www.lorinserchina.com.cn",
"firstWord"=>"L",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"劳伦士（Lorinser) 创立于1935年，工厂坐落在德国斯图加特，是专为梅赛德斯-奔驰精装升级的工厂。在维持梅赛德斯-奔驰原创精神和品种形象的大前提下，做最大幅度的提升。",

"companyName"=>"劳伦士",
"foreignName"=>"Lorinser",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>"0",
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:10:34",
"message"=>"0",
"source"=>1,
"carscmsId"=>57,
"carscmsCountry"=>"德国",
"sort"=>"",
),

"5"=>array
(
"id"=>59,
"brandName"=>"雷诺",
"logo"=>"http://img.emao.net/car/logo/nd/bah/gveo.png",
"website"=>"http://www.renault.cn/",
"firstWord"=>"L",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"雷诺汽车公司",
"foreignName"=>"Renault S.A",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:11:44",
"message"=>"0",
"source"=>1,
"carscmsId"=>60,
"carscmsCountry"=>"法国",
"sort"=>"",
),

"6"=>array
(
"id"=>60,
"brandName"=>"理念",
"logo"=>"http://img.emao.net/car/logo/nd/bah/bxyc.png",
"website"=>"http://www.chinalinian.com/Index.html",
"firstWord"=>"L",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",

"companyName"=>"理念",
"foreignName"=>"EVERUS",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:12:19",
"message"=>"0",
"source"=>1,
"carscmsId"=>61,
"carscmsCountry"=>"中国",
"sort"=>"",
),

"7"=>array
(
"id"=>63,
"brandName"=>"林肯",
"logo"=>"http://img.emao.net/car/logo/nd/bah/dcgc.png",
"website"=>"http://www.lincoln.com/",
"firstWord"=>"L",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"林肯轿车",
"foreignName"=>"LINCOLN",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:13:12",
"message"=>"0",
"source"=>1,
"carscmsId"=>64,
"carscmsCountry"=>"美国",
"sort"=>"",
),

"8"=>array
(
"id"=>64,
"brandName"=>"铃木",
"logo"=>"http://img.emao.net/car/logo/nd/bah/kodj.png",
"website"=>"http://www.suzuki-china.com/",
"firstWord"=>"L",
"ssi"=>"0",
"csi"=>"0",
"classId"=>1,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"铃木公司",
"foreignName"=>"SUZUKI",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:13:38",
"message"=>"0",
"source"=>1,
"carscmsId"=>65,
"carscmsCountry"=>"日本",
"sort"=>"",
),

),

"N"=>array
(
"0"=>array
(
"id"=>148,
"brandName"=>"南京金龙",
"logo"=>"http://img.emao.net",
"website"=>"",
"firstWord"=>"N",
"ssi"=>"",
"csi"=>"",
"classId"=>2,
"intro"=>"",
"companyName"=>"",
"foreignName"=>"",
"address"=>"",
"foundDate"=>"",
"meaning"=>"",
"scope"=>"",
"staff"=>"",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>"0",
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"",
"message"=>"0",
"source"=>1,
"carscmsId"=>1379,
"carscmsCountry"=>"自主",
"sort"=>"",
),

),

"Y"=>array
(
"0"=>array
(
"id"=>20,
"brandName"=>"野马汽车",
"logo"=>"http://img.emao.net/car/logo/nd/bah/laou.png",
"website"=>"http://www.yemaauto.cn/",
"firstWord"=>"Y",
"ssi"=>"0",
"csi"=>"0",
"classId"=>2,
"intro"=>"<br/>local Test<br/>",
"companyName"=>"四川汽车工业股份有限公司",
"foreignName"=>"sichuanqichegongye",
"address"=>"",
"foundDate"=>"0000-00-00",
"meaning"=>"",
"scope"=>"",
"staff"=>"0",
"founder"=>"",
"slogan"=>"",
"story"=>"",
"recommend"=>"0",
"hot"=>"0",
"hotRank"=>"0",
"state"=>1,
"addtime"=>"2014-10-21 01:07:36",
"updatetime"=>"2015-03-26 19:34:33",
"message"=>"0",
"source"=>1,
"carscmsId"=>20,
"carscmsCountry"=>"中国",
"sort"=>"",
),

),

),

"searchParam"=>array
(
"sellType"=>"0",
"brandId"=>"0",
"carriageId"=>"0",
"price"=>"0",
"carFrom"=>"0",
"isActivity"=>"0",
"priceSort"=>"0",
),

"count"=>26,
"carList"=>array
(
"0"=>array
(
"id"=>1856,
"consumerId"=>23252,
"sellType"=>2,
"brandId"=>143,
"subBrandId"=>194,
"serieId"=>1430,
"autoId"=>"0",
"smsTitle"=>"巨惠购车活动巨惠购车活动",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"",
"insertTime"=>"0",
"updateTime"=>1453115115,
"submitUser"=>"root",
"submitTime"=>1453115086,
"checkUser"=>"root",
"checkTime"=>1453115096,
"backTime"=>"",
"preSellTime"=>1453114800,
"sellTime"=>1453114800,
"underUser"=>"",
"underTxt"=>"",
"under"=>1,
"endSellTime"=>1459423800,
"endSellCount"=>"0",
"isDel"=>"0",
"delUser"=>"",
"delTime"=>"",
"sort"=>"0",
"sortState"=>"0",
"description"=>"巨惠购车活动巨惠购车活动",
"isRefund"=>1,
"discountWay"=>"0",
"discount"=>"0",
"contractNo"=>20160118,
"finalTime"=>"",
"sellLead"=>"巨惠购车活动巨惠购车活动",
"num"=>"0",
"minPrice"=>"0",
"invoice"=>"0",
"goodsCat"=>38,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>"",
"autoName"=>"",
"fullPayOn"=>1,
"isPurchase"=>"0",
"ticketCount"=>"0",
"goodsName"=>"巨惠购车活动",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>"",
"insertSource"=>"",
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":143,\"subBrandId\":194,\"serieId\":1430,\"autoId\":11719}",
"isInstallment"=>2,
"sortPrice_will_delete"=>"",
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>"0.00",
"defPrice"=>"0.00",
"isShopshow"=>2,
"tpl"=>8,
"multiple"=>"0",
"emaoPriceDisplay"=>"0元",
"sellTimeFormat"=>"2016/01/18,19:00:00",
"endSellTimeFormat"=>"2016/03/31,19:30:00",
"group"=>array
(
"id"=>37,
"gId"=>1856,
"entryPrice"=>1.00,
"minGroupnum"=>10,
"maxGroupnum"=>"0",
"setDiscount"=>2,
"everyAddnum"=>"0",
"everyDiscount"=>"0.00",
"isShowprice"=>1,
"isGrouprefund"=>1,
"serieNames"=>array
(
"0"=>array
(
"brandId"=>11,
"subBrandId"=>20,
"serieId"=>207,
"brandName"=>"比亚迪",
"subBrandName"=>"比亚迪",
"serieName"=>"比亚迪G3",
),

"1"=>array
(
"brandId"=>11,
"subBrandId"=>20,
"serieId"=>204,
"brandName"=>"比亚迪",
"subBrandName"=>"比亚迪",
"serieName"=>"比亚迪F3",
),

"2"=>array
(
"brandId"=>143,
"subBrandId"=>194,
"serieId"=>1522,
"brandName"=>"北汽新能源",
"subBrandName"=>"北汽新能源",
"serieName"=>"北汽新能源EV160",
),

"3"=>array
(
"brandId"=>143,
"subBrandId"=>194,
"serieId"=>1466,
"brandName"=>"北汽新能源",
"subBrandName"=>"北汽新能源",
"serieName"=>"北汽新能源EV200",
),

"4"=>array
(
"brandId"=>143,
"subBrandId"=>194,
"serieId"=>1465,
"brandName"=>"北汽新能源",
"subBrandName"=>"北汽新能源",
"serieName"=>"北汽新能源ES210",
),

"5"=>array
(
"brandId"=>143,
"subBrandId"=>194,
"serieId"=>1430,
"brandName"=>"北汽新能源",
"subBrandName"=>"北汽新能源",
"serieName"=>"北汽新能源E150EV",
),

),

"content"=>"巨惠购车活动巨惠购车活动",
"tuanHuodongtime"=>"",
"groupNum"=>"0",
"serieNamesString"=>"比亚迪,北汽新能源",
),

"couponInfo"=>array
(
),

"fall"=>"0",
"mainImg"=>"http://img.emao.net/mall/nd/zw/dnor.jpg",
"secImg"=>array
(
),

),

"1"=>array
(
"id"=>1854,
"consumerId"=>23255,
"sellType"=>2,
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>68,
"autoId"=>633,
"smsTitle"=>"巨惠购抵扣券－优惠抵扣金-20160118",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"root",
"insertTime"=>1453114749,
"updateTime"=>1453114814,
"submitUser"=>"root",
"submitTime"=>1453114783,
"checkUser"=>"root",
"checkTime"=>1453114792,
"backTime"=>"",
"preSellTime"=>1453114800,
"sellTime"=>1453114800,
"underUser"=>"",
"underTxt"=>"",
"under"=>1,
"endSellTime"=>1459422000,
"endSellCount"=>"0",
"isDel"=>"0",
"delUser"=>"",
"delTime"=>"",
"sort"=>"0",
"sortState"=>"0",
"description"=>"巨惠购抵扣券－优惠抵扣金-20160118巨惠购抵扣券－优惠抵扣金-20160118巨惠购抵扣券－优惠抵扣金-20160118巨惠购抵扣券－优惠抵扣金-20160118巨惠购抵扣券－优惠抵扣金-20160118",
"isRefund"=>1,
"discountWay"=>"0",
"discount"=>"0",
"contractNo"=>20160118,
"finalTime"=>1453114200,
"sellLead"=>"巨惠购抵扣券－优惠抵扣金-20160118",
"num"=>400,
"minPrice"=>0.01,
"invoice"=>"0",
"goodsCat"=>37,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>45.70,
"autoName"=>"",
"fullPayOn"=>"0",
"isPurchase"=>"0",
"ticketCount"=>10,
"goodsName"=>"巨惠购抵扣券－优惠抵扣金-20160118",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>"",
"insertSource"=>0001,
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":99,\"autoId\":827}",
"isInstallment"=>2,
"sortPrice_will_delete"=>"",
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>0.01,
"defPrice"=>45.70,
"isShopshow"=>2,
"tpl"=>6,
"multiple"=>"0",
"emaoPriceDisplay"=>"0.01元",
"sellTimeFormat"=>"2016/01/18,19:00:00",
"endSellTimeFormat"=>"2016/03/31,19:00:00",
"group"=>array
(
"id"=>35,
"gId"=>1854,
"entryPrice"=>"0.00",
"minGroupnum"=>20,
"maxGroupnum"=>"0",
"setDiscount"=>2,
"everyAddnum"=>1,
"everyDiscount"=>0.10,
"isShowprice"=>1,
"isGrouprefund"=>1,
"serieNames"=>"",
"content"=>"",
"tuanHuodongtime"=>"",
"groupNum"=>"0",
"serieNamesString"=>"",
"curDiscount"=>"1000",
"maxDiscount"=>"0",
"groupPrice"=>"0",
),

"couponInfo"=>array
(
"id"=>468,
"gid"=>1854,
"sellPrice"=>0.01,
"faceValue"=>1,
"couponDesc"=>"0.01元抵用１元",
),

"fall"=>727000.99,
"mainImg"=>"http://img.emao.net/mall/nd/zw/ktmb.jpg",
"secImg"=>array
(
),

),

"2"=>array
(
"id"=>1853,
"consumerId"=>23255,
"sellType"=>2,
"brandId"=>5,
"subBrandId"=>7,
"serieId"=>63,
"autoId"=>490,
"smsTitle"=>"巨惠购抵扣券－无优惠-20160118巨惠购抵扣券－无优惠-20",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"root",
"insertTime"=>1453114105,
"updateTime"=>1453114158,
"submitUser"=>"root",
"submitTime"=>1453114131,
"checkUser"=>"root",
"checkTime"=>1453114138,
"backTime"=>"",
"preSellTime"=>1453113000,
"sellTime"=>1453113000,
"underUser"=>"",
"underTxt"=>"",
"under"=>1,
"endSellTime"=>1462012200,
"endSellCount"=>"0",
"isDel"=>"0",
"delUser"=>"",
"delTime"=>"",
"sort"=>"0",
"sortState"=>"0",
"description"=>"<br/>local Test<br/>",
"isRefund"=>1,
"discountWay"=>"0",
"discount"=>"0",
"contractNo"=>001,
"finalTime"=>1464708600,
"sellLead"=>"巨惠购抵扣券－无优惠-20160118",
"num"=>300,
"minPrice"=>0.01,
"invoice"=>"0",
"goodsCat"=>37,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>32.80,
"autoName"=>"",
"fullPayOn"=>"0",
"isPurchase"=>"0",
"ticketCount"=>"0",
"goodsName"=>"巨惠购抵扣券－无优惠-20160118",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>"",
"insertSource"=>0001,
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":8,\"serieId\":67,\"autoId\":579}",
"isInstallment"=>2,
"sortPrice_will_delete"=>"",
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>0.01,
"defPrice"=>32.80,
"isShopshow"=>2,
"tpl"=>6,
"multiple"=>"0",
"emaoPriceDisplay"=>"0.01元",
"sellTimeFormat"=>"2016/01/18,18:30:00",
"endSellTimeFormat"=>"2016/04/30,18:30:00",
"group"=>array
(
"id"=>34,
"gId"=>1853,
"entryPrice"=>"0.00",
"minGroupnum"=>"0",
"maxGroupnum"=>"0",
"setDiscount"=>3,
"everyAddnum"=>"0",
"everyDiscount"=>"0.00",
"isShowprice"=>1,
"isGrouprefund"=>1,
"serieNames"=>"",
"content"=>"",
"tuanHuodongtime"=>"",
"groupNum"=>"0",
"serieNamesString"=>"",
"curDiscount"=>"11000",
"maxDiscount"=>"0",
"groupPrice"=>"0",
),

"couponInfo"=>array
(
"id"=>467,
"gid"=>1853,
"sellPrice"=>0.10,
"faceValue"=>1,
"couponDesc"=>"0.1元抵扣券价值１元",
),

"fall"=>396800.99,
"mainImg"=>"http://img.emao.net/mall/nd/zw/ievf.jpg",
"secImg"=>array
(
),

),

"3"=>array
(
"id"=>1848,
"consumerId"=>23252,
"sellType"=>2,
"brandId"=>11,
"subBrandId"=>20,
"serieId"=>218,
"autoId"=>"0",
"smsTitle"=>"个人中心巨惠购活动商品",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"",
"insertTime"=>"0",
"updateTime"=>1453105813,
"submitUser"=>"mall@emao.com",
"submitTime"=>1453105774,
"checkUser"=>"mall@emao.com",
"checkTime"=>1453105783,
"backTime"=>"",
"preSellTime"=>1453104000,
"sellTime"=>1453104000,
"underUser"=>"",
"underTxt"=>"",
"under"=>1,
"endSellTime"=>1454074200,
"endSellCount"=>"0",
"isDel"=>"0",
"delUser"=>"mall@emao.com",
"delTime"=>1453105122,
"sort"=>"0",
"sortState"=>"0",
"description"=>"个人中心巨惠购活动商品",
"isRefund"=>1,
"discountWay"=>"0",
"discount"=>"0",
"contractNo"=>"个人中心巨惠购活动商品",
"finalTime"=>"",
"sellLead"=>"个人中心巨惠购活动商品",
"num"=>"0",
"minPrice"=>"0",
"invoice"=>"0",
"goodsCat"=>38,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>"",
"autoName"=>array
(
"0"=>array
(
"brandId"=>11,
"subBrandId"=>20,
"serieId"=>210,
"brandName"=>"比亚迪",
"subBrandName"=>"比亚迪",
"serieName"=>"比亚迪L3",
),

"1"=>array
(
"brandId"=>7,
"subBrandId"=>11,
"serieId"=>113,
"brandName"=>"北汽制造",
"subBrandName"=>"北京汽车制造厂",
"serieName"=>"战旗",
),

"2"=>array
(
"brandId"=>11,
"subBrandId"=>20,
"serieId"=>218,
"brandName"=>"比亚迪",
"subBrandName"=>"比亚迪",
"serieName"=>"比亚迪G5",
),

),

"fullPayOn"=>1,
"isPurchase"=>1,
"ticketCount"=>"0",
"goodsName"=>"个人中心巨惠购活动商品",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>"",
"insertSource"=>"",
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":11,\"subBrandId\":20,\"serieId\":207,\"autoId\":1491}",
"isInstallment"=>2,
"sortPrice_will_delete"=>"",
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>"0.00",
"defPrice"=>"0.00",
"isShopshow"=>2,
"tpl"=>8,
"multiple"=>"0",
"emaoPriceDisplay"=>"0元",
"sellTimeFormat"=>"2016/01/18,16:00:00",
"endSellTimeFormat"=>"2016/01/29,21:30:00",
"group"=>array
(
"id"=>29,
"gId"=>1848,
"entryPrice"=>38.00,
"minGroupnum"=>5,
"maxGroupnum"=>38,
"setDiscount"=>1,
"everyAddnum"=>"0",
"everyDiscount"=>"0.00",
"isShowprice"=>1,
"isGrouprefund"=>1,
"serieNames"=>array
(
"0"=>array
(
"brandId"=>11,
"subBrandId"=>20,
"serieId"=>210,
"brandName"=>"比亚迪",
"subBrandName"=>"比亚迪",
"serieName"=>"比亚迪L3",
),

"1"=>array
(
"brandId"=>7,
"subBrandId"=>11,
"serieId"=>113,
"brandName"=>"北汽制造",
"subBrandName"=>"北京汽车制造厂",
"serieName"=>"战旗",
),

"2"=>array
(
"brandId"=>11,
"subBrandId"=>21,
"serieId"=>218,
"brandName"=>"比亚迪",
"subBrandName"=>"比亚迪",
"serieName"=>"比亚迪G5",
),

"3"=>array
(
"brandId"=>2,
"subBrandId"=>3,
"serieId"=>9,
"brandName"=>"奥迪",
"subBrandName"=>"一汽奥迪",
"serieName"=>"奥迪A6L",
),

"4"=>array
(
"brandId"=>11,
"subBrandId"=>20,
"serieId"=>218,
"brandName"=>"比亚迪",
"subBrandName"=>"比亚迪",
"serieName"=>"比亚迪G5",
),

),

"content"=>"个人中心巨惠购活动商品",
"tuanHuodongtime"=>1452843000,
"groupNum"=>5,
"serieNamesString"=>"比亚迪,北京汽车制造厂,一汽奥迪",
),

"couponInfo"=>array
(
),

"fall"=>"0",
"mainImg"=>"http://img.emao.net/mall/nd/zw/iwzy.jpg",
"secImg"=>array
(
),

),

"4"=>array
(
"id"=>1706,
"consumerId"=>23234,
"sellType"=>2,
"brandId"=>21,
"subBrandId"=>33,
"serieId"=>362,
"autoId"=>12997,
"smsTitle"=>234,
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"huangxiaowei539@emao.com",
"insertTime"=>1445592724,
"updateTime"=>1447240516,
"submitUser"=>"huangxiaowei539@emao.com",
"submitTime"=>1445592776,
"checkUser"=>"huangxiaowei539@emao.com",
"checkTime"=>1445592782,
"backTime"=>"",
"preSellTime"=>1443605400,
"sellTime"=>1445506200,
"underUser"=>"",
"underTxt"=>"",
"under"=>1,
"endSellTime"=>1455053400,
"endSellCount"=>"0",
"isDel"=>"0",
"delUser"=>"",
"delTime"=>"",
"sort"=>"0",
"sortState"=>"0",
"description"=>234,
"isRefund"=>1,
"discountWay"=>1,
"discount"=>1111,
"contractNo"=>342134213,
"finalTime"=>1445592600,
"sellLead"=>"为儿女",
"num"=>7,
"minPrice"=>34,
"invoice"=>"0",
"goodsCat"=>33,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>15.08,
"autoName"=>array
(
"brandId"=>21,
"subBrandId"=>33,
"serieId"=>362,
"autoId"=>12997,
"brandName"=>"大众",
"subBrandName"=>"一汽-大众",
"serieName"=>"高尔夫",
"autoName"=>"1.2TSI 自动舒适型",
"year"=>"1.2TSI 自动舒适型",
),

"fullPayOn"=>1,
"isPurchase"=>"0",
"ticketCount"=>3,
"goodsName"=>"2015-1.2TSI 自动舒适型",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>2,
"insertSource"=>"",
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":21,\"subBrandId\":33,\"serieId\":362,\"autoId\":2844}",
"isInstallment"=>1,
"sortPrice_will_delete"=>34.00,
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>34.00,
"defPrice"=>15.08,
"isShopshow"=>2,
"tpl"=>3,
"multiple"=>"0",
"emaoPriceDisplay"=>"34元",
"sellTimeFormat"=>"2015/10/22,17:30:00",
"endSellTimeFormat"=>"2016/02/10,05:30:00",
"group"=>array
(
"serieNames"=>"",
"serieNamesString"=>"",
),

"couponInfo"=>array
(
),

"fall"=>150766,
"mainImg"=>"http://img.emao.net/mall/nd/zz/hmfr.png",
"secImg"=>array
(
),

),

"5"=>array
(
"id"=>1628,
"consumerId"=>23236,
"sellType"=>2,
"brandId"=>21,
"subBrandId"=>33,
"serieId"=>366,
"autoId"=>3008,
"smsTitle"=>"2015-3.0FSI V6lqx定制车有优惠券3张",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"liqiaoxia381@emao.com",
"insertTime"=>1442285911,
"updateTime"=>1451113526,
"submitUser"=>"liqiaoxia381@emao.com",
"submitTime"=>1442386804,
"checkUser"=>"liqiaoxia381@emao.com",
"checkTime"=>1442386810,
"backTime"=>"",
"preSellTime"=>1442386800,
"sellTime"=>1442386800,
"underUser"=>"root",
"underTxt"=>"",
"under"=>2,
"endSellTime"=>1459407600,
"endSellCount"=>3,
"isDel"=>"0",
"delUser"=>"",
"delTime"=>"",
"sort"=>"0",
"sortState"=>"0",
"description"=>"2015-3.0FSI V6lqx定制车有优惠券3张",
"isRefund"=>1,
"discountWay"=>"0",
"discount"=>"0",
"contractNo"=>1,
"finalTime"=>1456540200,
"sellLead"=>"2015-3.0FSI V6lqx定制车有优惠券3张",
"num"=>148,
"minPrice"=>"0",
"invoice"=>1,
"goodsCat"=>33,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>34.28,
"autoName"=>array
(
"brandId"=>21,
"subBrandId"=>33,
"serieId"=>366,
"autoId"=>3008,
"brandName"=>"大众",
"subBrandName"=>"一汽-大众",
"serieName"=>"大众CC",
"autoName"=>"2015-3.0FSI V6",
"year"=>2015,
),

"fullPayOn"=>1,
"isPurchase"=>"0",
"ticketCount"=>"0",
"goodsName"=>"2015-3.0FSI V6lqx定制车有优惠券3张",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>4,
"insertSource"=>"",
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"isInstallment"=>1,
"sortPrice_will_delete"=>"0.00",
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>"0.00",
"defPrice"=>34.28,
"isShopshow"=>2,
"tpl"=>3,
"multiple"=>"0",
"emaoPriceDisplay"=>"0元",
"sellTimeFormat"=>"2015/09/16,15:00:00",
"endSellTimeFormat"=>"2016/03/31,15:00:00",
"group"=>array
(
"serieNames"=>"",
"serieNamesString"=>"",
),

"couponInfo"=>array
(
),

"fall"=>342800,
"mainImg"=>"http://img.emao.net/mall/nd/bai/jvwx.jpg",
"secImg"=>array
(
),

),

"6"=>array
(
"id"=>1606,
"consumerId"=>23202,
"sellType"=>2,
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>78,
"autoId"=>781,
"smsTitle"=>"李巧霞测试整车",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"root",
"insertTime"=>1441797637,
"updateTime"=>1447240110,
"submitUser"=>"liqiaoxia381@emao.com",
"submitTime"=>1442290306,
"checkUser"=>"liqiaoxia381@emao.com",
"checkTime"=>1442290362,
"backTime"=>"",
"preSellTime"=>1442289600,
"sellTime"=>1442289600,
"underUser"=>"",
"underTxt"=>"",
"under"=>1,
"endSellTime"=>1460001600,
"endSellCount"=>1,
"isDel"=>"0",
"delUser"=>"",
"delTime"=>"",
"sort"=>"0",
"sortState"=>"0",
"description"=>"李巧霞测试整车",
"isRefund"=>1,
"discountWay"=>1,
"discount"=>1000,
"contractNo"=>"李巧霞测试整车",
"finalTime"=>1441797540,
"sellLead"=>"李巧霞测试整车",
"num"=>6,
"minPrice"=>20000,
"invoice"=>"0",
"goodsCat"=>15,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>67.30,
"autoName"=>array
(
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>78,
"autoId"=>781,
"brandName"=>"宝马",
"subBrandName"=>"宝马(进口)",
"serieName"=>"宝马3系GT",
"autoName"=>"335i  设计套装型",
"year"=>2014,
),

"fullPayOn"=>1,
"isPurchase"=>"0",
"ticketCount"=>"0",
"goodsName"=>"2014-335i  设计套装型",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>2,
"insertSource"=>"",
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"isInstallment"=>2,
"sortPrice_will_delete"=>20000.00,
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>20000.00,
"defPrice"=>67.30,
"isShopshow"=>2,
"tpl"=>1,
"multiple"=>"0",
"emaoPriceDisplay"=>"2.00万",
"sellTimeFormat"=>"2015/09/15,12:00:00",
"endSellTimeFormat"=>"2016/04/07,12:00:00",
"group"=>array
(
"serieNames"=>"",
"serieNamesString"=>"",
),

"couponInfo"=>array
(
),

"fall"=>653000,
"mainImg"=>"",
"secImg"=>array
(
),

),

"7"=>array
(
"id"=>1549,
"consumerId"=>23226,
"sellType"=>4,
"brandId"=>"0",
"subBrandId"=>"0",
"serieId"=>"0",
"autoId"=>"0",
"smsTitle"=>"",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"liqiaoxia381@emao.com",
"insertTime"=>1441004962,
"updateTime"=>1442290386,
"submitUser"=>"root",
"submitTime"=>1441614337,
"checkUser"=>"root",
"checkTime"=>1441704636,
"backTime"=>"",
"preSellTime"=>1442289600,
"sellTime"=>1442289600,
"underUser"=>"",
"underTxt"=>"",
"under"=>1,
"endSellTime"=>1460001600,
"endSellCount"=>"0",
"isDel"=>"0",
"delUser"=>"",
"delTime"=>"",
"sort"=>"0",
"sortState"=>"0",
"description"=>"",
"isRefund"=>1,
"discountWay"=>"0",
"discount"=>"0",
"contractNo"=>1,
"finalTime"=>1441004760,
"sellLead"=>"",
"num"=>"0",
"minPrice"=>"0",
"invoice"=>1,
"goodsCat"=>27,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>99999999.00,
"autoName"=>"",
"fullPayOn"=>"0",
"isPurchase"=>1,
"ticketCount"=>"0",
"goodsName"=>"抵扣券的",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>"",
"insertSource"=>0001,
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"isInstallment"=>2,
"sortPrice_will_delete"=>"0.00",
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>999999999.00,
"defPrice"=>99999999.00,
"isShopshow"=>2,
"tpl"=>2,
"multiple"=>"0",
"emaoPriceDisplay"=>"100000.00万",
"sellTimeFormat"=>"2015/09/15,12:00:00",
"endSellTimeFormat"=>"2016/04/07,12:00:00",
"group"=>array
(
"serieNames"=>"",
"serieNamesString"=>"",
),

"couponInfo"=>array
(
"id"=>340,
"gid"=>1549,
"sellPrice"=>"0",
"faceValue"=>10000,
"couponDesc"=>1,
),

"mainImg"=>"http://img.emao.net/mall/nd/bai/cbvt.jpg",
"secImg"=>array
(
),

),

"8"=>array
(
"id"=>1392,
"consumerId"=>23202,
"sellType"=>2,
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"smsTitle"=>"2整自采-普通售卖-无订金不全款-不可退款2015-Acti",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"root",
"insertTime"=>1439881337,
"updateTime"=>1452592977,
"submitUser"=>"liqiaoxia381@emao.com",
"submitTime"=>1442290330,
"checkUser"=>"liqiaoxia381@emao.com",
"checkTime"=>1442290362,
"backTime"=>"",
"preSellTime"=>1442289600,
"sellTime"=>1442289600,
"underUser"=>"",
"underTxt"=>"",
"under"=>2,
"endSellTime"=>1460001600,
"endSellCount"=>2,
"isDel"=>"0",
"delUser"=>"",
"delTime"=>1439892848,
"sort"=>"0",
"sortState"=>"0",
"description"=>"<br/>local Test<br/>",
"isRefund"=>"0",
"discountWay"=>"0",
"discount"=>"0",
"contractNo"=>"zhengche-20150818002",
"finalTime"=>1439911800,
"sellLead"=>"1整车自采-普通售卖-无订金不全款-不可退款2015-ActiveHybrid 3",
"num"=>42,
"minPrice"=>"0",
"invoice"=>"0",
"goodsCat"=>15,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>66.80,
"autoName"=>array
(
"brandId"=>5,
"subBrandId"=>8,
"serieId"=>67,
"autoId"=>609,
"brandName"=>"宝马",
"subBrandName"=>"宝马(进口)",
"serieName"=>"宝马3系(进口)",
"autoName"=>"2015-ActiveHybrid 3",
"year"=>2015,
),

"fullPayOn"=>1,
"isPurchase"=>1,
"ticketCount"=>"0",
"goodsName"=>"整车自采-普通售卖-无订金不全款-不可退款2015-ActiveHybrid 3",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>1,
"carriage"=>2,
"insertSource"=>"",
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"isInstallment"=>1,
"sortPrice_will_delete"=>"0.00",
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>"0.00",
"defPrice"=>66.80,
"isShopshow"=>2,
"tpl"=>1,
"multiple"=>"0",
"emaoPriceDisplay"=>"0元",
"sellTimeFormat"=>"2015/09/15,12:00:00",
"endSellTimeFormat"=>"2016/04/07,12:00:00",
"group"=>array
(
"serieNames"=>"",
"serieNamesString"=>"",
),

"couponInfo"=>array
(
),

"fall"=>668000,
"mainImg"=>"http://img.emao.net/mall/nd/bai/crxo.jpg",
"secImg"=>array
(
"0"=>"http://img.emao.net/mall/nd/bai/kjwj.jpg",
"1"=>"http://img.emao.net/mall/nd/bai/bhoo.jpg",
"2"=>"http://img.emao.net/mall/nd/bai/kdvb.jpg",
),

),

"9"=>array
(
"id"=>1385,
"consumerId"=>23222,
"sellType"=>2,
"brandId"=>10,
"subBrandId"=>17,
"serieId"=>185,
"autoId"=>1268,
"smsTitle"=>"抵扣券不可议价格",
"pcContent"=>"<br/>local Test<br/>",
"mContent"=>"<br/>local Test<br/>",
"state"=>5,
"insertUser"=>"liqiaoxia381@emao.com",
"insertTime"=>1439806453,
"updateTime"=>1442290386,
"submitUser"=>"liqiaoxia381@emao.com",
"submitTime"=>1439806613,
"checkUser"=>"liqiaoxia381@emao.com",
"checkTime"=>1441614080,
"backTime"=>"",
"preSellTime"=>1442289600,
"sellTime"=>1442289600,
"underUser"=>"",
"underTxt"=>"",
"under"=>1,
"endSellTime"=>1460001600,
"endSellCount"=>"0",
"isDel"=>"0",
"delUser"=>"",
"delTime"=>1439892848,
"sort"=>"0",
"sortState"=>"0",
"description"=>"抵扣券不可议价格",
"isRefund"=>1,
"discountWay"=>"0",
"discount"=>"0",
"contractNo"=>1,
"finalTime"=>1441359000,
"sellLead"=>"抵扣券不可议价格",
"num"=>7,
"minPrice"=>22,
"invoice"=>"0",
"goodsCat"=>27,
"goodsType_will_delete"=>1,
"salestate"=>"",
"price"=>21.78,
"autoName"=>array
(
"brandId"=>10,
"subBrandId"=>17,
"serieId"=>185,
"autoId"=>1268,
"brandName"=>"本田",
"subBrandName"=>"东风本田",
"serieName"=>"本田CR-V",
"autoName"=>"2.0L四驱经典版",
"year"=>2013,
),

"fullPayOn"=>"0",
"isPurchase"=>"0",
"ticketCount"=>2,
"goodsName"=>"抵扣券不可议价格",
"stockType"=>1,
"isTest"=>2,
"bargainType"=>2,
"carriage"=>8,
"insertSource"=>"",
"insertUserId"=>"",
"autoImages"=>"{\"brandId\":5,\"subBrandId\":9,\"serieId\":102,\"autoId\":830}",
"isInstallment"=>2,
"sortPrice_will_delete"=>"0.00",
"isActivity"=>2,
"isSeckill"=>2,
"defemaoPrice"=>22.00,
"defPrice"=>21.78,
"isShopshow"=>2,
"tpl"=>2,
"multiple"=>6,
"emaoPriceDisplay"=>"22元",
"sellTimeFormat"=>"2015/09/15,12:00:00",
"endSellTimeFormat"=>"2016/04/07,12:00:00",
"group"=>array
(
"serieNames"=>"",
"serieNamesString"=>"",
"curDiscount"=>"0",
"maxDiscount"=>"0",
"groupPrice"=>"0",
),

"couponInfo"=>array
(
"id"=>203,
"gid"=>1385,
"sellPrice"=>"0",
"faceValue"=>10000,
"couponDesc"=>"",
),

"fall"=>227778,
"mainImg"=>"http://img.emao.net/mall/nd/bai/edht.jpg",
"secImg"=>array
(
"0"=>"http://img.emao.net/mall/nd/bai/csym.jpg",
"1"=>"http://img.emao.net/mall/nd/bai/myny.jpg",
"2"=>"http://img.emao.net/mall/nd/bai/vlz.jpg",
),

),

),

"pageTitle"=>"一猫新车商城在售车型列表和最新汽车报价_网购汽车最新报价大全_一猫新车商城",
"pageKeyword"=>"一猫新车商城,一猫商城,一猫汽车,网上汽车商城,在线买车,特价车商城,汽车商城,买车网,购车网",
"pageDescription"=>"北京一猫新车商城是新型的网商购车体验平台，为用户提供在线购买汽车服务并可享受一猫网全程专业的选车、选商家等指导服务，还可以获得现金优惠券加油卡等礼包。买车上一猫。",
"__loginInfo"=>array
(
),

"__serverTime"=>1453175826,
"__serverTimeFormat"=>"2016/01/19,11:57:06",
"__http"=>array
(
"mall"=>"http://mall.emao.com",
"mall_m"=>"http://mall.m.emao.com",
"temai"=>"http://mall.emao.com",
"temai_m"=>"http://mall.m.emao.com",
"i"=>"http://i.emao.com",
"i_m"=>"http://i.m.emao.com",
),

),

);